datasync/chaindatafetcher/kafka/kafka_test.go
=> kafka: Relax kafka_test timeout

accounts/abi/bind/backends/simulated.go, blockchain/state_transition.go, blockchain/system/rebalance.go, blockchain/system/rebalance_test.go, consensus/istanbul/backend/engine.go
- Remove unused `getBurnAmountMagma` function
- Relocate the treasury rebalance memo logging site from system.RebalanceTreasury to engine.Finalize
- SimulatedBackend.SuggestGasPrice returns lastBaseFee*2 or UnitPrice depending on fork level.
=> Tidy RebalanceTreasury and SimulatedBackend

api/api_public_blockchain.go, api/api_public_transaction_pool.go, consensus/istanbul/backend/api.go
- GetTransactionByHash and RpcOutputReceipt passes null to the parameter block of newRPCTransaction. So the calculation of effectiveGasPrice couldn't work.
- This PR fixes those functions to pass actual Header.
=> api: pass actual Header through newRPCOutput function

reward/supply_manager.go
- This PR set kairos testnet burnt amount correctly for totalSupply api. This change is applied only when `chainid==kairosNetworkId(1001)` and the memo is `before` (check memo output here https://baobab.klaytnscope.com/account/0x3D478E73c9dBebB72332712D7265961B1868d193?tabId=contractCode)
Tested at private network and the burnt amount is changed like below. This is testnet so zeroed and allocated amount is not set or balance …
=> api: set kairos testnet burnt amount correctly for totalSupply api

accounts/abi/bind/backends/blockchain.go, accounts/abi/bind/backends/blockchain_test.go, accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go, client/kaia_client.go, interfaces.go, node/sc/remote_backend.go
- Add KIP-162 support to the Go client for the RPC (kaia_client and sc/remote_backend).
=> interface: Add CallMsg.GasFeeCap,GasTipCap

contracts/contracts/system_contracts/consensus/PublicDelegation/PublicDelegationStorage.sol, contracts/test/CnV3/cnStakingV3.test.ts, contracts/test/PublicDelegation/publicDelegation.test.ts
Allow 100% commission rate for public delegation.
TODO: Deploy public delegation factory accordingly.
=> Update max commission rate of public delegation

.github/PULL_REQUEST_TEMPLATE.md, api/api_private_account.go, api/api_public_transaction_pool.go
Remove klaytn from ecrecover error message.
Fix PR template.
=> Remove klaytn from ecrecover error

api/api_ethereum.go, api/api_private_account.go, api/api_public_transaction_pool.go
- There were two different message signing standards in Klaytn
- [EIP-191](https://eips.ethereum.org/EIPS/eip-191). Prepend `"\x19Ethereum Signed Message:\n" + len(message)` to the message before signing
- [KIP-97](https://github.com/klaytn/kips/blob/main/KIPs/kip-97.md). Prepend `"\x19Klaytn Signed Message:\n" + len(message)` to the message before signing
- In this PR,
- Message signing RPCs (i.e. signature producers) are now EIP-191 compliant
- Message verifying RPCs (i.e. signature consumers) accept both EIP and KIP if possible, only EIP otherwise. 
| RPC                     	| Implementation                              	| Before PR          	| After PR           	|
|-------------------------	|---------------------------------------------	|--------------------	|--------------------	| …
=> api: Message signing RPCs are EIP-191 compliant

blockchain/blockchain.go, blockchain/vm/call_tracer.go, blockchain/vm/evm.go, blockchain/vm/internaltx_tracer.go, datasync/chaindatafetcher/chaindata_fetcher.go, node/cn/tracers/api.go, node/cn/tracers/tracers_test.go
- Follow-up of #15.
- debug RPC API
- `callTracer` was previously `call_tracer.js` and is now `vm.CallTracer`
- `fastCallTracer` was previously `vm.InternalTxTracer` and is now `vm.CallTracer`
- chaindatafetcher
- `ChainEvent.InternalTxTraces` (enabled when `--vm.internaltx`) was previously produced by `vm.InternalTxTracer` and is now `vm.CallTracer`, but preserves the original `InternalTxTrace` output format.
If this is a …
=> tracers: debug APIs and chaindatafetcher use new vm.CallTracer

client/kaia_client.go
- This PR fixes `SendUnsignedTransaction` to pass the `txtype` when converting arguments through `toSendTxArgs`.
=> pass txType when sendUnsignedTransaction at kaia_client.go

blockchain/system/multicall.go, blockchain/system/multicall_test.go, common/refcntmap.go, node/cn/state_accessor.go, reward/staking_manager.go, tests/state_reexec_test.go, tests/testutil_blockchain_test.go
- Affects
- `debug_trace*` APIs on full-mode nodes may have returned incorrect results if the traced transaction touches any validator reward address. e.g. interaction with PublicDelegation contracts. Archive-mode nodes are unaffected.
- Background
- State regeneration (or reexec) is a process of generating the world state at a given block when the state is not in the database. It works by re-executing the transactions (and post-transaction state transitions by `Finalize()`), starting from the nearest block in which the state exists in the database.
- State regen is primarily used in debug trace APIs. In those APIs, a block or a transaction is executed against a historic block state. To support this API even in full nodes, the block state is regenerated if not exist in the database.
- …
=> reward: Fix state regeneration with post-Kaia staking info

node/cn/gasprice/gasprice.go, node/cn/gasprice/gasprice_test.go
Now SuggestTipCap has 0 default tip cap. It might return 0 tip even when `baseFee > lowerBound` when early congestion situation. So we might need to handle this if needed.
```
64 25 0 	 0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0 	 25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
65 26 0 	 0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,2 	 25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,26
^ Network becomes busy, but have 0 tip
66 27 0 	 0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,2,2 	 25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,26,27
67 28 0 	 0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,2,2,2 	 25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,26,27,28
68 30 0 	 0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,2,2,2,2 	 25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,26,27,28,30
69 31 0 …
```
=> Update SuggestTipCap default tip cap

blockchain/vm/internaltx_trace_json.go
- Fixes chaindatafetcher trace output to include the new `revertReason` field
=> vm: InternalTxTrace JSON includes revertReason

consensus/clique/clique.go, consensus/consensus.go, consensus/gxhash/consensus.go, consensus/istanbul/backend/api.go, consensus/istanbul/backend/engine.go, consensus/mocks/engine_mock.go, datasync/chaindatafetcher/kafka/repository.go, governance/api.go, node/cn/backend.go, reward/staking_manager.go, reward/supply_manager_test.go
This PR is similar with #46 except that it only regenerates and preloads staking info at node start up. The existing APIs will bubble up if user requests info at stateless block (or blocks).
How it differs from #46:
| | #46 | This PR |
|---|---|---|
| Startup | regen | regen |
| APIs | regen | bubble up missing state error ("missing trie node") |
<details>
<summary>APIs example</summary>
```
// No snapshot cache
> kaia.getCommittee("20")
Error: missing trie node d9c413d220797a666c786380e0f269b1f228304601cdc492c66eb40bdc2efc28 (path )
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:18(3)
// No snapshot cache
> kaia.getBlockWithConsensusInfo
kaia.getBlockWithConsensusInfo kaia.getBlockWithConsensusInfoRange
> istanbul.getValidators(30)
Error: missing trie node …
```
=> Preload staking info only at startup

governance/api.go
This PR is on top of #48
`GetRewardsAccumulated` has deadlock at `reqCh<-num` when `len(errCh)>numWorkers` since non-nil error closes goroutine. This PR makes separate goroutine for requests.
<details><summary>Console test</summary>
```
// Before PR
> governance.getRewardsAccumulated(700, 701)
Error: missing trie node e58fbf31ca5b4a4c5e2435f37fa0e87bbec954f1900d2f4da9810eab9b39214b (path )
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:33(4)
> governance.getRewardsAccumulated(700, 1700)
...
^ deadlock occurs
// After PR
> governance.getRewardsAccumulated(700, 1700)
Error: missing trie node 31371ed81cf6c6d0df48d2b5d61414a6e695aa6390f45fef50290d3d13295021 (path )
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:33(4)
> governance.getRewardsAccumulated(700, …
```
=> Fix deadlock in GetRewardsAccumulated

contracts/contracts/system_contracts/allocation/Airdrop.sol, contracts/contracts/system_contracts/allocation/IAirdrop.sol, contracts/test/Allocation/airdrop.test.ts, contracts/test/common/fixtures.ts
Update `Airdrop.sol` contract.
1. Add `claimAllowed` to control claim.
2. Add `receiver` function to allow `airdrop` to receive funds.
- This is because we may need to send funds to `Airdrop` not through state modification.
3. Owner can override registered claim.
- Note that it doesn't change `claimed`, but only `claims`.
5. Tidy comments and functions.
If this is a relatively large or complex change, kick off the discussion …
=> Update airdrop contract

api/api_public_klay.go, networks/rpc/handler.go, reward/supply_manager.go, reward/supply_manager_test.go
1. In the `kaia_getTotalSupply` API, add an optional `showPartial *bool` parameter that controls the error behavior.
- As-is: API returns...
- (a) Return a full information or
- (b) Return a partial information
- To-be: API returns..
- **Regular use case**: If `showPartial == nil || *showPartial == false` (default)
- (a) Return a full information or
- (c) API Fails. If `--upstream-en` is configured and the error contains "missing trie node", retry with upstream.
- **Advanced/Debugging use case**: If `*showPartial == true`
- (a) Return a full information or
- (b) Return a partial information
2. More generous `--upstream-en` criteria
- Updated `shouldRequestUpstream()` to recognize a wrapped error that contains "missing trie node" error.
Regular users of this API are interested in the full …
=> api: getTotalSupply can fall back to Upstream EN

cmd/utils/flags.go, node/config.go, storage/database/db_manager.go, storage/database/pebbledb_database.go
- This PR adds some level related pebbledb metrics. Also, it adds `PebbleDB` dbtype option since it was missing.
- Some metrics are not matched 100% between leveldb and pebbledb, so be pay attention when comparing those metrics.
For example, one of the level related pebbledb metric, `klaytn_klay_db_chaindata_statetrie_0levelN_size (N=0~6)` is now available in pebbleDB.
=> db: adjust pebbledb metric

node/cn/backend.go, reward/supply_manager.go, reward/supply_manager_test.go
- Address the issue where an archive node not serving `kaia_getTotalSupply` for non-128-multiple blocks.
- Cause
- SupplyManager writes `AccReward` every BlockInterval. The intention was to make full nodes write every `BlockInterval` whereas archive nodes write every `1` block.
- In reality, archive nodes may set `BlockInterval == 128 (default)` because it didn't matter so far. The [writeStateTrie loop](https://github.com/kaiachain/kaia/blob/v1.0.1/blockchain/blockchain.go#L1363) ignores BlockInterval when gcmode is archive.
- Therefore, SupplyManager didn't store `AccReward` every `1` block. Rather it stored every 128 blocks in archive nodes with default settings.
- Fix
- Have SupplyManager calculate `AccReward` for any given block, by re-accumulating from the nearest persisted …
=> reward: SupplyManager reaccumulates from nearest persisted AccReward

contracts/docs/CnStakingV2.md, contracts/docs/PublicDelegation.md, contracts/docs/voting.md
Fixed a few typos and grammar for clarity. Hope this helpful.
=> chore: fix typos and refine texts

console/web3ext/web3ext.go
- JS console supports the parameter introduced by #58.
```
// all of them supported
kaia.getTotalSupply(0x19c4e00)
kaia.getTotalSupply(0x19c4e00, false)
kaia.getTotalSupply(0x19c4e00, true)
```
=> console: kaia.getTotalSupply accepts second optional param

blockchain/blockchain.go, node/cn/api_backend.go, node/cn/api_backend_test.go, node/cn/backend.go, params/governance_params.go, reward/supply_manager.go, reward/supply_manager_test.go, storage/database/schema.go
- The GetTotalSupply API had a bug that over-accumulates TotalMinted and TotalBurnt after a manual block rewinding via `debug_setHead`. See https://app.circleci.com/pipelines/github/kaiachain/kaia/355/workflows/a330fe31-08f5-4771-bd3a-3459d4849a70/jobs/1776 and `reward/supply_manager_test.go:TestCatchupRewind` for the test reproducing it.
1. SupplyManager catchup thread is guarded against out-of-order ChainHeadEvent that might be emitted after block rewind (i.e. debug_setHead)
2. Block rewind (i.e. BlockChain.setHeadBeyondRoot) involves deletion of SupplyCheckpoints, and restarting the catchup thread.
3. Invalidate existing supply checkpoints (dubbed "accRewards"), triggers every node upgrading to v1.0.2 re-accumulate from the genesis. Because of the bug, nodes v1.0.1 or earlier which …
=> reward: SupplyManager correctly handles block rewinds

api/api_public_transaction_pool.go
- `kaia_recoverFromTransaction` now works with Ethereum tx types (types 0,1,2).
- #70
=> api: Fix recoverFromTransaction with Legacy type

console/jsre/deps/web3.js
As-is
```
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "latest2")
Error: the header does not exist (block number: 30506450030916658)
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:13(4)
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "www")
"0x"
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "wwwwqnfqwfnkn")
Error: invalid argument 1: hex number > 64 bits
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:13(4)
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "wwwwqnfqwfn^C
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "wwwwqnfqwfnkn")
Error: invalid argument 1: hex number > 64 bits
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:13(4)
> …
```
=> console: Sanitization in inputBlockNumberFormatter

governance/api.go
Next methods were crashed with "pending" or future block number.
* `kaia.getStakingInfo(99999999)`
* `kaia.getRewards(99999999)`, `kaia.getRewards("pending")`
```
> kaia.getRewards(99999999)
Error: method handler crashed
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:16(3)
```
This PR fixes it, and now it returns `currentblock information`(pending) or `unknown block error`(future block).
```
> kaia.getRewards("pending")
{
burntFee: 0,
kef: 0,
kif: 0,
minted: 9600000000000000000,
proposer: 9600000000000000000,
rewards: {
0xf19ebf7b5766528b190e4a1b8073a0f1b6901c8b: 9600000000000000000
},
stakers: 0,
totalFee: 0
}
> kaia.getRewards(99999999)
Error: Unknown block
at web3.js:6812:9(39)
at send (web3.js:5223:62(29))
at <eval>:1:16(3)
```
Please put an x in the boxes related to …
=> api: do not crash with unknown blocknumber input

blockchain/blockchain.go, blockchain/state/database.go, common/lru/basiclru.go, common/lru/basiclru_test.go, common/lru/blob_lru.go, common/lru/blob_lru_test.go, common/lru/lru.go, go.mod, go.sum, snapshot/disklayer.go, snapshot/snapshot.go
- This PR is brought from ethereum to fix the oom issue when calling debug api repeatedly. (e.g. once every 10 seconds)
- https://github.com/kaiachain/kaia/issues/75
=> state: replace fastcache with gc-friendly structure

api/api_ethereum.go, api/api_ethereum_test.go, api/api_public_blockchain.go, api/api_public_blockchain_test.go, api/tx_args.go, console/web3ext/web3ext.go
Overwrite state if the `overrides` fields is given in `kaia_estimateGas` and `eth_estimateGas` APIs.
Geth has updated the `override.Apply()` function, a new feature that modifies the precompiled contract address, but it is not imported in this PR. (also, this feature is not triggered against `EstimateGas` API)
Example usage:
```sh
#!/bin/bash
curl -X 'POST' \
'http://localhost:8551' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"method": "kaia_estimateGas",
"id": 1,
"jsonrpc": "2.0",
"params": [
{
"from": "0x9a8d1dfdad4806605e3c63067897e4f13b06a5b4",
"to": "0x10235AC9fCb213e1B229f636913637CD35Bf4031",
"gas": "0x1cbf1",
"value": "0x0",
"gasPrice":"0x5d21dba00",
"input": "0xe3dc878300000000000000000000000000000000000000000000000000000000000004d2"
},
"0x7bd", …
```
=> [API] Interleaved state override to `EstimateGas`

storage/database/db_manager.go
Resolve https://github.com/klaytn/klaytn/issues/1412
As-Is
```
do state migration (copy database)
mark the completion
remove old database
```
To-Be
```
do state migration (copy database)
remove old database
mark the completion
```
During the database deletion process, failures may occur due to common errors with os.RemoveAll(). The function marks the operation as complete regardless of whether the deletion was successful or not.
- Please leave the issue numbers or links related to this PR …
=> [StateMigration] Mark the completion mark once deletion is done

consensus/istanbul/core/vrank.go
Vrank logs are not currently being collected due to datadog issue, so lower the log level for reducing log file size.
=> Lower log level of vrank

blockchain/blockchain.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, kaiax/README.md, kaiax/interface.go, kaiax/noop/api.go, kaiax/noop/consensus.go, kaiax/noop/execution.go, kaiax/noop/init.go, kaiax/noop/txprocess.go, kaiax/noop/types/interface.go, log/log_modules.go, node/cn/api_backend.go, node/cn/api_backend_test.go, node/cn/backend.go, work/mocks/blockchain_mock.go, work/work.go
- Define "kaiax modules" similar to "x/modules" of Cosmos SDK. See kaiax/interface.go for the design.
- Add NoopModule as a template.
- A JsonRpcModule can be injected into the `CN` to expose its APIs
- A ConsensusModule can be injected into a `ConsensusModuleHost`; currently the only host is the Istanbul backend.
- An ExecutionModule can be injected into an `ExecutionModuleHost`; where the only host is BlockChain.
- A RewindableModule can be injected into an `RewindableModuleHost`; where the only host is BlockChain.
- TxProcessModule and TxPoolModule are left as future work.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> kaiax: Add module framework and dummy noop module

governance/api.go
`kaia_getParams`, `governance_getParams`, `kaia_getChainConfig`, `governance_getChainConfig` APIs to override deprecated parameters depending on hardfork level. Namely,
- since Kore, `reward.useginicoeff` is `false` as All committee members have an equal chance of being elected block proposers https://github.com/klaytn/klaytn/pull/1655
- since Randao, `reward.proposerupdateinterval` is `1` as proposer list is no longer used, rather proposers are selected every block at random. (https://github.com/klaytn/klaytn/pull/2030)
- since Kaia, `reward.stakingupdateinterval` is `1` as staking information is updated every block, effectively deprecating the interval. (https://github.com/klaytn/klaytn/pull/2154)
Though these fields could be deleted later as in #91, we first return the close-to-reality …
=> governance: APIs override deprecated parameters

blockchain/blockchain.go, consensus/istanbul/backend/engine.go, kaiax/noop/consensus.go, kaiax/noop/execution.go, kaiax/noop/txprocess.go, node/cn/backend.go, work/work.go, work/worker.go
1. Fix in `VerifyHeader`: `sb.verifyCascadingFields` returns `errEmptyCommittedSeals` for 1 CN, so execute the module first. (This error is handled [here](https://github.com/kaiachain/kaia/blob/feat/kaiax/consensus/istanbul/backend/backend.go#L366))
2. Add in `writeBlockWithState`: because the proposer does not execute `insertChain`.
Proposer log
```
INFO[09/20,11:55:13 +09] [58|kaiax/noop/consensus.go:30]                 NoopModule PrepareHeader                  blockNum=2
INFO[09/20,11:55:13 +09] [58|kaiax/noop/consensus.go:35]                 NoopModule FinalizeHeader                 blockNum=2
INFO[09/20,11:55:13 +09] [51|work/worker.go:633]                         Commit new mining work                    number=2 hash=992222…c72086 txs=0 elapsed=5.211ms   commitTime=4.739ms …
```
=> kaiax: Fix execution location

build/ci.go
- This PR adds build tags for building statically linked kaia binaries
- Some glibc features (e.g., libnss) can cause dependencies on specific version of glibc.
- To avoid using such features, we can add build tags to guide go compiler (and linker) to use Golang implementation (as an alternative to the related glibc feature)
- This is a [known](https://go-review.googlesource.com/c/go/+/92456) [issue](https://github.com/golang/go/issues/26492) in Golang, and also a mitigation adopted in [geth](https://github.com/ethereum/go-ethereum/blob/ec69830b6f4520c0d847cad3cf61d8a4da9db178/build/ci.go#L265)
The following build method now produces a fully static binary.
```sh
KAIA_STATIC_LINK=1 make ken
```
_Put an x in the boxes that apply. You can …
=> Update build tags for static link

.circleci/config.yml, build/package-tar.sh
- The supported architecture for pre-built binaries were `linux-amd64`, `darwin-arm64`
- This PR adds linux-arm64 tar/rpm package build jobs which generates `linux-arm64` pre-built binaries.
=> build: add pre-built binary for linux-arm64 architecture

.circleci/config.yml
- The upload packages to s3 repo is failing when tagging v1.0.3-rc.2. It is because s3 command cannot upload multiple files together.
- This PR makes aws s3 command handles one file at one time.
=> ci: fix upload-packages-to-s3 script

consensus/istanbul/validator/weighted.go
This PR fixed not to touch nil validator pointer if found.
The `valSet` in snapshot might contain demoted proposers if the CN's total staking amount became lower than 5M KAIA but not removed from validators explicitly.
Even before Kaia HF, potential nil dereference pointer must be prevented. …
=> Skip nil validator for snapshot

.circleci/config.yml, Makefile, build/Dockerfile-go1.20.6-solc0.8.13-ubuntu, build/Dockerfile-ubuntu-18.04-go1.20.6-solc0.8.13, build/ci.go, build/linter/golangci-exhaustive.yml, build/linter/golangci-try.yml, build/linter/golangci.yml, kaiax/gov/headergov/impl/consensus.go, kaiax/gov/param.go, kaiax/gov/param_test.go, kaiax/gov/paramset.go, kaiax/gov/paramset_test.go
This PR introduces an exhaustive linter for enums. It prevents mistakes when adding a new element to enum.
Also, refactor `build/ci.go` to use config files like [geth](https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L481-L498).
- Now, circle CI additionally runs `golangci-lint` command (i.e., exhaustive linter on `kaiax`) during `test-linters` job.
- Before, `lint-try` executed `golangci-lint` 6 times. Now, it runs all flags in a batch and executes just `golangci-lint` once.
- Before, `lint-try` produced output to `linter_report.txt`. Now it outputs `linter_report.html` based on `build/linter/golangci-try.yml`.
If an enum is missing from switch statement, linter outputs an error:
```
kaiax/gov/paramset.go:128:3: missing cases in switch of type gov.ParamName: …
```
=> kaiax/gov: Add exhaustive linter & remove reflect

console/console.go
The purpose here should be to initialize a slice with a capacity of len(call.Arguments)  and a length of 0, and then append it later. Instead of initializing the length to  len(call.Arguments)  from the beginning, the resulting slice will not meet expectations.
The online demo: https://go.dev/play/p/q1BcVCmvidW
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> fix: fix slice init length

blockchain/state/statedb.go
In `statedb.Copy()`, the `stateObjectsDirtyStorage` map isn't initialized so it may lead to nil map error. This PR suggests to initialize the map correctly. Note that I didn't copy entries from journal since it's redundant.
This can be triggered when using copied state for `blockchain.ApplyTransaction()` which calls `statedb.Finalise(true, setStorageRoot=false)`. In `Finalise`, it tries to mark the `stateObjectsDirtyStorage` but will be panic since copied `statedb` holds nil map.
The exact panic point is: https://github.com/kaiachain/kaia/blob/dev/blockchain/state/state_object.go#L408
I checked the current code and it seems there's no affected part so far.
_Put an x in the boxes that apply. You can also fill these out after creating the …
=> statedb: Initialize dirty storage map correctly

kaiax/gov/headergov/impl/consensus.go, kaiax/gov/headergov/impl/error.go, kaiax/gov/headergov/impl/execution.go, kaiax/gov/headergov/impl/getter.go, kaiax/gov/headergov/impl/getter_test.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/impl/init_test.go, kaiax/gov/headergov/impl/schema.go, kaiax/gov/impl/init.go, node/cn/backend.go
This PR introduces an "anchor" block number (`governanceLowestVoteScannedBlockNum` in code), which indicates that the block numbers larger than the anchor has been scanned and saved into `governanceVoteDataBlockNums` DB.
The anchor is decremented by an epoch after scanning all the headers to record all blocks with votes.
Therefore, the retrieval logic is different depending on whether the blocks in a given epoch are greater than anchor or not. See `getVotesInEpoch`.
```
lowestVoteScannedBlock                     HEAD
0                                  V                                 V
|..................................|.................................|
votes not saved                     votes saved in DB/memory
header scan required
```
Service log
```
INFO[10/22,17:36:57 +09] …
```
=> Kaiax/gov: use both old and new DB schema

blockchain/types/account/account_test.go
- Add AccountSerializer tests to check RLP and JSON encoding of EOAs and SCAs.
- Use hardcoded and hand-crafted test cases
- Remove round-trip (encode->decode->encode) test cases that cannot ensure backward-compatibility.
- This PR checks the pre-7702 (original) behavior.
- This PR is independent of #119. You can merge it anytime.
- #126 can build on this PR to add further test cases.
If this is a relatively large or complex …
=> types: Add AccountSerializer tests

kaiax/gov/headergov/impl/api_test.go, kaiax/gov/headergov/impl/execution.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/vote.go, kaiax/gov/headergov/vote_test.go, kaiax/gov/param.go, kaiax/gov/param_test.go
- Facilitates `governance_vote` to support validator votes (i.e., `governance.addvalidator`/`governance.removevalidator`).
- Adds address-list encoding in `ToVoteBytes`.
- Adds address-list canonicalizer `validatorAddressListCanonicalizer`.
- Adds `ValidatorParams` for checking validator-related votes.
- Adds testcases from real blocks: `TestVoteSerialization`.
This PR fixes encoding of multiple-address votes, because the previous scheme involves decoding RLP twice.
This data does not exist in any on-chain blocks, so there's no need to support backward compatibility.
```
// before this PR
rlp decode 0xf85b94f39fd6e51aad88f6f4ce6ab8827279cfffb922669a676f7665726e616e63652e72656d6f766576616c696461746f72ea943c44cdddb6a900fa2b585dd299e03d12fa4293bc9490f79bf6eb2c4f870365e785982e1f101e93b906 …
```
=> kaiax/gov: Serialize/deserialize validator votes

networks/rpc/handler.go
This PR suggests to show the error comes from the upstream archive EN, not itself.
```
// Before
> kaia.getBalance("0x0d019776cf279ba6a0d93bf63c83ab1104287008", "23")
Error: the header does not exist (block number: 23)
at web3.js:6814:9(39)
at send (web3.js:5225:62(29))
at <eval>:1:16(4)
```
```
// After
> kaia.getBalance("0x0d019776cf279ba6a0d93bf63c83ab1104287008", "23")
Error: from upstream archive en: the header does not exist (block number: 23)
at web3.js:6814:9(39)
at send (web3.js:5225:62(29))
at <eval>:1:16(4) (edited) 
```
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
=> Improve error message for upstream request

api/api_ethereum.go, api/api_ethereum_test.go, api/api_public_blockchain.go, api/backend.go, consensus/istanbul/backend/api.go, datasync/chaindatafetcher/kafka/utils.go, node/cn/api_backend.go, node/cn/api_backend_test.go
This PR removes `totalDifficulty`(`eth` namespace) and `totalBlockScore`(`kaia` namespace) according to https://github.com/ethereum/execution-apis/pull/570
As-Is:
```
> eth.getHeaderByNumber(kaia.blockNumber)
{
baseFeePerGas: "0x5d21dba00",
...
...
timestamp: "0x673e7f0f",
totalDifficulty: "0x10294",
transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
}
```
This PR:
```
> eth.getHeaderByNumber(kaia.blockNumber)
{
baseFeePerGas: "0x5d21dba00",
...
...
timestamp: "0x673e8215",
transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
}
```
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …
=> api: Remove `totalDifficulty` and `totalBlockScore` field in RPC output

params/bootnodes.go
- Let PNs have the BN address by default, eliminating the need of `BOOTNODES=` setting in kpnd.conf.
- The BN addresses are identical to ENBNs because we don't operate separate PNBNs.
=> params: Add default BN addresses for PNs

networks/p2p/discover/table.go
Suppose a program bonds to a node once and exits before committing to the database via tab.copyBondedNodes or db.updateNode. Next time this program launches and tries to tab.Bond a node, it will receive db.node(id) = nil, then never bonding to the node. This patch can recover from such absence of database entry.
It has to do with following three NodeDB schemas:
- db.node(id): Node information. Periodically committed by the [`copyBondedNode` loop](https://github.com/kaiachain/kaia/blob/c1f9ef577b7066cd0f3503fae64523a3f574f481/networks/p2p/discover/table.go#L472-L473), [every 30 seconds](https://github.com/kaiachain/kaia/blob/c1f9ef577b7066cd0f3503fae64523a3f574f481/networks/p2p/discover/table.go#L435).
- db.findFails(id): Number of times the node failed to respond to `findnode` request. …
=> p2p: Relaxed Bond pingpong condition

kaiax/gov/contractgov/interface.go, kaiax/gov/headergov/impl/execution_test.go, kaiax/gov/headergov/impl/getter.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/impl/rewind.go, kaiax/gov/headergov/interface.go, kaiax/gov/impl/getter.go, kaiax/gov/impl/getter_test.go, kaiax/gov/impl/init.go, kaiax/gov/impl/init_test.go, kaiax/gov/impl/mock/blockchain_mock.go, kaiax/gov/interface.go, kaiax/gov/param.go, kaiax/gov/param_test.go, node/cn/backend.go, tests/gov_test.go
This PR adds a fallback to kaiax/gov, so the fallback chain is ContractGov -> HeaderGov -> ChainConfig (`m.Fallback`) -> Default values.
See further comments regarding why ChainConfig fallback is necessary.
This PR also fix some bugs; fix deadlock at rewind, use relative path for go:generate.
If all below conditions are true, ChainConfig fallback is required:
- a parameter is not in `Genesis header`'s Governance.
- a parameter's value of `Genesis ChainConfig` is different from the `Default Value`.
On Mainnet/Kairos, DeriveShaImpl satisfies all the condition.
On Private net, new parameters can satisfy all the condition, when `Magma hardfork block > 0` and/or `Kore hardfork block > 0` and ChainConfig of `genesis.json` contains non-default value.
<details>
<summary>Details</summary>
- …
=> kaiax/gov: Add ChainConfig fallback

api/tx_args.go, client/kaia_client.go
- Add authorizationList to the arg of send transaction.
- When using SetCodeTxType, input common.Address to value instead of a pointer from arg.
=> Add authorizationList to the arg of send transaction

blockchain/blockchain_test.go, blockchain/state/statedb.go, blockchain/state_transition.go, blockchain/state_transition_test.go, blockchain/vm/interface.go, blockchain/vm/mocks/statedb_mock.go
- KIP228 has newly clarified the `CodeInfo`, so we will follow up on that.
- https://github.com/kaiachain/kips/pull/32
- `GetVmVersion` should always return (0, false) or (1, true) when the account is EOA.
- In `SetCodeToEOA`, we also have to change state of `CodeInfo`.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> Set the EOA CodeInfo correctly

node/node.go
A node may find other peers from bootnode (when discovery enabled), static-nodes, trusted-nodes, and contents of nodeDB (i.e. DATA_DIR/klay/nodes). When none of those are given, this node cannot connect to any node, failing to download blocks.
A common mistake is to run a node with `ken --networkid 8217`, where the node launches in private net mode. This node 
will be given no bootnodes, thus no connection to any peers. In this particular example, the correct way is to using `ken --mainnet`.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> p2p: Warn when none of bn,static,trusted nodes are given

blockchain/state/statedb.go, blockchain/state_transition.go, node/cn/tracers/tracers_test.go, tests/state_test.go, tests/state_test_util.go, tests/vm_test_util.go
This PR enables 7702 tests using `execution-spec-test` and fixes some bugs.  Some tests skip because of some reasons.
main commit: https://github.com/kaiachain/kaia/pull/149/commits/536532b86877078b62ae5f0dc1e1b93de4a31f53
skip tests:
- These files can't be loaded because of json format error
- prague/eip7702_set_code_tx/set_code_txs/invalid_tx_invalid_auth_signature.json
- prague/eip7702_set_code_tx/set_code_txs/tx_validity_chain_id.json
- prague/eip7702_set_code_tx/set_code_txs/tx_validity_nonce.json
bug fix:
- fix the condition when setting `obj.created = true`
- fix to increment nonce for each SetCode tx
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> test: Enable 7702 tests using `execution-spec-tests`

blockchain/vm/interpreter.go, blockchain/vm/jump_table.go
In the fix for #119, we mistakenly added enable7702 to the cancun instruction set.
- Take the Prague instructions and set the correct instructions for the fork.
=> core/vm: Fix wrong enable Prague(7702) instruction

accounts/abi/bind/backends/blockchain.go, api/api_ethereum_test.go, blockchain/blockchain.go, blockchain/state_transition.go, cmd/homi/genesis/options.go, cmd/utils/nodecmd/chaincmd.go, consensus/istanbul/backend/backend_test.go, consensus/istanbul/backend/testutil_test.go, governance/default.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/impl/init_test.go, kaiax/gov/impl/init.go, kaiax/staking/impl/api.go, node/cn/backend.go, node/cn/config.go, node/cn/gasprice/gasprice.go, node/cn/gasprice/gasprice_test.go, tests/kaia_test_blockchain_test.go, work/work.go, work/worker.go
This PR is a sequel of #162.
<details>
<summary>MixedEngine method replaced by GovModule</summary>
It excludes `governance` directory, as they will be removed.
</details>
<details>
<summary>MixedEngine methods that will be completely removed by ValSet module</summary>
These will be removed after introducing ValSet module.
- UpdateParams
- CanWriteGovernanceState
- WriteGovernanceState
- ClearVotes
- WriteGovernanceForNextEpoch
- UpdateCurrentSet
- HandleGovernanceVote
- Votes
- SetTotalVotingPower
- SetMyVotingPower
- SetBlockchain
</details>
<details>
<summary>ChainConfig replaced by GovModule</summary>
</details>
<details>
<summary>ChainConfig left as-is</summary>
There are cases when the genesis chain config can be used. Either it's immutable, or not essential to use the latest value. …
=> kaiax/gov: Replace remaining with gov

blockchain/state/statedb.go, blockchain/state/statedb_test.go, blockchain/types/account/account_test.go, blockchain/types/account/externally_owned_account.go
This PR suggests:
1. Copy all fields including EIP-7702 specific in `DeepCopy()`. Without this, dirtied EOA objects will have `default` values for each type, not `empty` values.
2. Use `ProgramAccount` to get the storage root.
3. Fix EIP-7702 related methods for EOA. (Only for testing) …
=> Add EIP-7702 compatibility

kaiax/valset/impl/getter_context.go, kaiax/valset/impl/init.go
- Fix out-of-bounds error in `selectRandaoCommittee`. The bug is triggered during `getProposer()` when qualified.Len < committeeSize
- Fix migration logic where LowestScannedVoteNum is updated only when necessary.
=> kaiax/valset: Fix selectRandaoCommittee and migration

blockchain/vm/instructions.go
- dev branch return bad block at baobab 14598509. (cypress also) and this PR fixes opExtCodeHash not to return bad block.
=> evm: EXTCODEHASH to return emptyCodeHash before Cancun

consensus/istanbul/backend/engine.go
The variable `valset`  may be nil and error check has been absent. This valset is used at L343 and leads to nil dereference if it is a nil. This PR adds a error check and returns error if it is not a nil.
It was discovered during setHead operation and this issue disappeared after restarting.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1850a8b]
goroutine 8515 [running]:
github.com/kaiachain/kaia/consensus/istanbul.(*BlockValSet).Qualified(...)
/home/ubuntu/QA/rc/consensus/istanbul/validator.go:148
github.com/kaiachain/kaia/consensus/istanbul/backend.(*backend).verifySigner(0x8de1bbfa50036df5?, {0xa4534502a3c86890?, 0x96e37b8244bcc2ea?}, 0xc020e48c88, {0xc0206b1b88?, 0x4a8fc40?, 0x2174b20?}) …
```
=> consensus: Added error check to valset

networks/rpc/handler.go
Decrease the `rpcPendingRequestsCount` accordingly.
The `rpcPendingRequestsCount` metrics should follow the `pendingRequestCount` metric, which is a counter that limits the number of concurrent RPC servings.
=> metrics: Decrease pending requests count

kaiax/reward/impl/getter.go, kaiax/reward/impl/getter_test.go, kaiax/staking/impl/getter.go
In previous PR #176, the CL info was filled since the `Prague + 1` block. But the CL staking info must be used for the Prague block. This PR makes staking modules to read CL for the Prague block.
Please note that it's safe to assume that `sourceBlockNum == number - 1` for the Prague block since Kaia hardfork must be the same or earlier than Prague fork.
<details><summary> kaia_getStakingInfo </summary>
`pragueCompatibleBlock == 50`
```
// Before this PR
> kaia.getStakingInfo(50)
{
KIRAddr: "0x6c38302e00dbac91712d93ab94b4a827698be6f1",
PoCAddr: "0xc8757a6b5b427ddcd5781c9faa5e41318d32336a",
blockNum: 49,
clStakingInfos: null,
councilNodeAddrs: ["0xad77f7306d42a03d35ab3ae3302a970de795157f", "0x2b9d1f31a860a5c6649b8a77b2a6b7530fdebe3c", "0xf7d662c06e09a19770eacf38199699a6c1a60bcf", …
```
=> kaiax/staking,reward: Use CL info since Prague block

blockchain/state/state_object.go, blockchain/state/statedb.go, blockchain/vm/evm.go, blockchain/vm/interface.go, blockchain/vm/mocks/statedb_mock.go
This PR bring EIP-7610 implementation. Please refer to original implementation [here](https://github.com/ethereum/go-ethereum/pull/28912).
Both EIP-684 and EIP-6710 apply retroactively for all blocks since genesis in Ethereum. In Kaia, since we already decided to introduce EIP-684 in Shanghai hardfork (not from genesis), I added EIP-6710 in Shanghai to align the activation. If you have other opinions, please let me know.
If …
=> blockchain/vm: reject contract creation to non-empty storage root

networks/p2p/discover/discover_storage_simple.go, networks/p2p/discover/discover_storage_simple_test.go, networks/p2p/discover/udp.go
- `discover.simpleStorage.closest` does not respect its parameter `nresults` and returns `simpleStorage.max` number of nodes.
- `discover.simpleStorage.add` does not respect `simpleStorage.max` and allows up to `math.MaxInt64` number of nodes.
None
=> Fix simpleStorage regarding maximum number of nodes

api/api_public_blockchain.go
The condition of basefee inclusion has been incorrectly placed. This results in a header having a zero base. Thus, hash of the header is not the same with the existing header hash (e.g., scope or scan). 
=> api: Fixed basefee field inclusion

blockchain/blockchain.go, blockchain/chain_makers.go, blockchain/types/tx_internal_data.go, blockchain/types/tx_internal_data_account_creation.go, blockchain/types/tx_internal_data_ethereum_access_list.go, blockchain/types/tx_internal_data_ethereum_dynamic_fee.go, blockchain/types/tx_internal_data_ethereum_set_code.go, blockchain/types/tx_internal_data_fee_delegated_smart_contract_deploy.go, blockchain/types/tx_internal_data_fee_delegated_smart_contract_deploy_with_ratio.go, blockchain/types/tx_internal_data_fee_delegated_value_transfer.go, blockchain/types/tx_internal_data_fee_delegated_value_transfer_memo.go, blockchain/types/tx_internal_data_fee_delegated_value_transfer_memo_with_ratio.go, blockchain/types/tx_internal_data_fee_delegated_value_transfer_with_ratio.go, blockchain/types/tx_internal_data_legacy.go, blockchain/types/tx_internal_data_serializer.go, blockchain/types/tx_internal_data_smart_contract_deploy.go, blockchain/types/tx_internal_data_value_transfer.go, blockchain/types/tx_internal_data_value_transfer_memo.go, blockchain/vm/contracts.go, blockchain/vm/evm.go, common/types.go, rlp/decode.go, tests/block_test.go, tests/block_test_util.go, tests/gen_btheader.go, tests/init.go, tests/init_test.go, tests/state_test.go, tests/state_test_util.go
This PR enables Shanghai, Cancun EETS blockchain testing with the Cancun and Prague forks.
The flow has been slightly changed to enable blockchain testing.
It includes some code to check for eth compatibility, but these may not be optimal. 
Please review these only for the logic to proceed with the test task first.
- [Decode tx](https://github.com/kaiachain/kaia/pull/211/commits/43b8342cc4d408befc6623ae96bc298a3aedfea2)
- Add some global variables as test flag
- https://github.com/kaiachain/kaia/pull/211/commits/4b6dce35b59048b95d734b063ae1cfdcc7fa5378#diff-37b6e7ed4f299b87b357b54376123393b34ee0699fc035f25bc0621627dcc6baR2736-R2739
- https://github.com/kaiachain/kaia/pull/211/commits/4b6dce35b59048b95d734b063ae1cfdcc7fa5378#diff-36960dea371fb7a7722f48b0905c890030f61801a29c132b5ade154357f0e …
=> test: Enable Shanghai and Cancun EIPs blockchain test by Cancun and Prague forks

blockchain/chain_makers.go, tests/block_test.go, tests/block_test_util.go
This PR enables prague's EIP7623 test in eets blockchain tests.
There was a problem with the test process that has now been fixed.
- It was not possible to create a block containing a transaction that returns an error using Generate chain. The test function makes this possible.
- https://github.com/kaiachain/kaia/issues/152#issuecomment-2597630897
- Skiped prague except 7702 - EIP7623
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> test: Enable prague's EIP7623

blockchain/chain_makers.go, blockchain/genesis.go, tests/block_test.go, tests/block_test_util.go
- Give the genesis.Alloc account a code format when running the EETS blockchain test. This will set precompile correctly.
- When calling `AddTxWithChainEvenHasError`, if it was given a bc, call `ApplyTransaction` using that vmConfig.
- Add params.OpcodeComputationCostLimitInfinite to the blockchain’s vmConfig
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …
=> test: EETS Set precompile correctly

Makefile, accounts/manager.go, api/backend.go, blockchain/vm/call_tracer.go, consensus/consensus.go, consensus/istanbul/backend.go, event/subscription.go, kaiax/gov/contractgov/interface.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/interface.go, kaiax/gov/impl/init.go, kaiax/gov/interface.go, kaiax/reward/interface.go, kaiax/staking/interface.go, kaiax/supply/interface.go, kaiax/valset/interface.go, node/cn/backend.go, node/cn/filters/filter.go, node/cn/peer.go, node/cn/peer_set.go, node/cn/protocol.go, node/sc/bridgepeer.go, node/sc/kas/anchor.go, node/sc/subbridge.go, storage/statedb/cache.go, work/work.go
The `devtools` task of `Makefile` is old. It doesn't work and can't do `go generate ./...`
Changes:
- Update `devtools` task to use `go install`
- Update `go:generate` directive
After this patch, it works
```
// Examples
go generate ./...
go generate ./accounts
go generate ./accounts/manager.go
```
=> build: update devtools of Makefile

tests/state_test.go, tests/tx_validation_test.go
fix some function names in comment
=> chore: fix some function names in comment

consensus/istanbul/backend/api.go
Fix wrong nil check for `istanbul.getDemotedValidatorsAtHash`.
=> backend: Fix wrong nil check

storage/database/db_manager.go
When state migration has been finished, it removes old DB and dbm for state migration. But setting the completion mark `inMigration = false` is done after `dbm.dbs[StateTrieMigrationDB] = nil` in separate go-routine (no lock held), which leads to potential nil dereference due to timing issue while opening a new trie (since it accesses to `dbm.dbs[StateTrieMigrationDB]` if `inMigration = true`).
I strongly suspect it's the root cause of the random test failure of `TestMigration_StartMigrationByMiscDBOnRestart` in CI.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …
=> Set completion mark in correct timing

blockchain/blockchain.go, blockchain/types/tx_internal_data.go, blockchain/types/tx_internal_data_serializer.go, tests/block_test.go, tests/block_test_util.go
We will remove some parts of the eets main code that added global variables and update it in the test engine.
- Remove GasLimitInExecutionSpecTest
- Remove UseKaiaCancunExtCodeHashFee
- Remove IsPragueInExecutionSpecTest
- Calculate the gas price based on the given base fee
- Self decode to convert to kaia's eth tx type
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> test: Remove some main code modifications in EETS

params/protocol_params.go
This PR changes the historical blockhash address for pectra-devnet-6. Almost same as #209.
Deployment account: `0x3462413Af4609098e1E27A490f554f260213D685`
Deployment tx: `0xf8838085e8d4a510008303d0908080b85c60538060095f395ff33373fffffffffffffffffffffffffffffffffffffffe14604657602036036042575f35600143038111604257611fff81430311604257611fff9006545f5260205ff35b5f5ffd5b5f35611fff600143030655001b820539930aa12693182426612186309f02cfe8a80a0000`
- https://github.com/ethereum/EIPs/pull/9287
If this …
=> params: Update EIP-2935 Historical blockhash contract for prectra-devnet-6

datasync/downloader/downloader.go, kaiax/staking/impl/execution.go, kaiax/staking/impl/init.go, kaiax/staking/impl/preload_buffer.go, node/cn/backend.go, node/cn/state_accessor.go
We've found there's a missing staking info issue after deleting CreateSnapshot at node startup. The staking info for the current block (=stateAt(parent)) is needed to validate that the peer is in validator sets if the node is CN. To fix this, I modified `kaiax/staking` module slightly.
- Cache the staking info at Preload.
- Purge cache at `RewindTo` for setHead operation.
- This is needed since the cached staking info will be purged at `Start` without this.
And in the downloader, it doesn't request a block range that contains current block when it is lower than `MaxHeaderFetch`, which results in missing staking info. Let's assume the current head is 74.
- As-Is:
- It requests peer the block for [0, 16, 32, 48, 64], not including 74.
- When the peer returns the header, it'll select 64 as a …
=> node: Fix missing staking info at node startup

build/rpm/etc/systemd/system/kbnd.service, build/rpm/etc/systemd/system/kcnd.service, build/rpm/etc/systemd/system/kend.service, build/rpm/etc/systemd/system/kpnd.service, build/rpm/etc/systemd/system/kscnd.service, build/rpm/etc/systemd/system/ksend.service, build/rpm/etc/systemd/system/kspnd.service, build/rpm/main.go
- kend rpm v1.0.3 had not been successfully installing on Rocky Linux 9. This PR makes rpm v2.0.0 work correctly.
- After installing the RPM package, following commands must work:
- SysVInit commands (requires `/etc/init.d/functions` and `/etc/init.d/k*nd` files)
```
/etc/init.d/kend {start|stop|restart|status}
```
- Systemd commands (additionally requires `/etc/systemd/system/k*nd.service` file)
```
systemctl {start|stop|restart|status} kend
```
- Note that `/etc/init.d/kend` depends on `/etc/init.d/functions` file. The RPM script also handles it.
- RPM package must be correctly installed in both cases:
- Clean install v2.0.0
- Upgrade from v1.0.3
- RPM package must be correctly installed on following environments:
- CentOS stream 9
- Rocky Linux 9
Please put an x in the boxes related to …
=> build: RPM package installs initscripts and systemd services

kaiax/gov/headergov/impl/getter.go, kaiax/gov/impl/getter.go, kaiax/gov/impl/init.go, kaiax/gov/paramset.go, tests/gov_test.go
Add `Crit` on unexpected error; it may be better to panic than to continue with invalid value.
For backward compatibility, fix the return type of `kaia_getParams` from int to string for `reward.mintingamount` and `reward.minimumstake`.
See https://github.com/kaiachain/kaia/issues/189#issuecomment-2609106572
=> kaiax/gov: add crits and fix kaia_getParams

tests/state_test_util.go
EEST has accounts which have empty code but non-empty storage as the pre state. Kaia should recognize the following:
- account with delegation code and fork is prague → EOA
- account with empty code but non-empty storage and fork is prague  → EOA
- account with non-empty code except for delegation code → SCA
- otherwise → as is
This PR enables to recognize accounts with empty code but non-empty storage as EOA.
If this is a …
=> tests: set accounts with empty code but non-empty storage as EOA

blockchain/state_migration.go, storage/database/db_manager.go, storage/database/schema.go, tests/state_migration_test.go
When the node stops while removing the old db, the state migration restarts from scratch. This PR sets the old db path before removal so the node can find a pending removal job when restarted. Inspired from https://github.com/kaiachain/kaia/pull/229#issuecomment-2611410684
Please note that PR #229 only fixes nil dereference issue.
The overall process will be:
1. Set the completion mark and old db path.
2. Start removing old db.
3. The node stops before completely removing the old db.
4. The node will find the old db path and remove it.
5. Set empty old db path.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …
=> storage/database: cleanup old database after migration

accounts/abi/bind/backends/blockchain.go, accounts/abi/bind/backends/simulated.go, api/api_public_blockchain.go, api/tx_args.go, blockchain/blockchain_test.go, blockchain/state_processor.go, blockchain/state_transition.go, blockchain/state_transition_test.go, blockchain/system/multicall.go, blockchain/system/rebalance.go, blockchain/types/transaction.go, blockchain/types/transaction_signing.go, blockchain/types/transaction_signing_test.go, blockchain/types/transaction_test.go, blockchain/types/tx_internal_data_ethereum_dynamic_fee.go, blockchain/types/tx_internal_data_ethereum_set_code.go, blockchain/types/tx_internal_data_serializer_test.go, blockchain/types/tx_internal_data_test.go, blockchain/vm/eips.go, blockchain/vm/instructions.go, tests/account_keytype_test.go, tests/gen_stauthorization.go, tests/state_test.go, tests/state_test_util.go, tests/tx_gas_calculation_test.go, tests/tx_validation_test.go
Changes:
* Use `uint256` for `SET_CODE_TX_TYPE(EIP-7702)`
* `EXTCODE*` return delegation designator for `SET_CODE_TX_TYPE(EIP-7702)`
* Enable to EEST of EIP-7702
* Thanks for these patches
* https://github.com/kaiachain/kaia/pull/245
* https://github.com/kaiachain/kaia/pull/247
- https://github.com/kaiachain/kaia/issues/106
- https://github.com/kaiachain/kaia/pull/216
- https://github.com/kaiachain/kaia/pull/233
=> feat: Use uint256 for chainId and return delegation designator for EXTCODE* in SET_CODE_TX_TYPE(EIP-7702)

blockchain/error.go, blockchain/state_transition.go, blockchain/state_transition_test.go, blockchain/tx_pool.go, blockchain/types/transaction.go, blockchain/types/tx_internal_data.go, tests/state_test.go, tests/tx_gas_calculation_test.go, tests/tx_gas_overflow_test.go
This PR fixes gas calculation logic for EIP-7623 changes introduced in #200 
Also, this PR fixes gas calculation tests accordingly.
Added state transition test for EIP-7623.
EIP-7623 states that the new formula for gas calculation as follows:
```
tx.gasUsed = (
21000
+
max(
STANDARD_TOKEN_COST * tokens_in_calldata
+ execution_gas_used
+ isContractCreation * (32000 + INITCODE_WORD_COST * words(calldata)),
TOTAL_COST_FLOOR_PER_TOKEN * tokens_in_calldata
)
)
```
Geth's implementation for above formula is:
```
max(total_gas_used, 21000 + floor_gas)
```
However Kaia has different `TxGas` for different tx types, for example fee delegated tx has `21000 + 10000`.
That would make our implementation:
```
max(total_gas_used, tx_gas_per_tx_type + floor_gas)
```
Furthermore, we have additional gas for …
=> Fix EIP-7623 gas calculation and tests

kaiax/reward/spec.go, kaiax/staking/staking_info.go
This PR revises some formats of reward and staking api responses.
1. In stakingInfo api, the empty NodeIds, RewardAddrs, StakingContracts, StakingAmounts returns `None`. But it should return []. So this PR supports [] format.
2. getRewardsAccumulated api's timestamp format is changed from UTC string to UNIX timestamp format.
- v1.0.3: 
```
> governance.getRewardsAccumulated(kaia.blockNumber-2, kaia.blockNumber)
{
firstBlock: 1080,
firstBlockTime: "2025-02-06 13:58:51 +0800 +08",
lastBlock: 1082,
lastBlockTime: "2025-02-06 13:58:53 +0800 +08",
...
}
```
- PR(will be included at v2.0.0):
```
> governance.getRewardsAccumulated(kaia.blockNumber-2, kaia.blockNumber)
{
firstBlock: 1117,
firstBlockTime: 1738821607,
lastBlock: 1119,
lastBlockTime: 1738821609,
...
}
```
Please put an x in the …
=> kaiax/staking: revise reward,staking api response format

blockchain/genesis.go, blockchain/genesis_test.go
This PR enables to make genesis blocks according to forks. **This may have braking change in the case where the fork of genesis is Istanbul fork and after because this changes the state root of genesis by changing codeinfo of SCA (version 0 into version 1).** But there is no effect against mainnet and testnet because the genesis doesn't have any forks. You can see the state roof of genesis doesn't change in [this test](https://github.com/kaiachain/kaia/blob/dde4921a5dfac10f9f2c392cbfc20c0f1a7072bd/blockchain/genesis_test.go#L41-L51).
This stores genesis accounts like bellow:
- account with delegation code and fork is prague → CreateEOA and SetCodeToEOA
- account with empty code but non-empty storage and fork is prague → CreateEOA
- account with non-empty code except for delegation code → …
=> blockchain: make a genesis block according to forks

tests/state_test.go
This PR organizes skipping state tests for EEST.
- `frontier/opcodes/all_opcodes/all_opcodes.json`: Kaia doesn't permit to execute precompiled contracts with value transfering. I think this is needed because we previously missed to add Prague instruction sets (#179).
- `frontier/precompiles/precompile_absence/precompile_absence.json`: Thises tests succeeded for Prague. These skip for only Cancun. The reason of failure in Cancun is the same as `eip2537_bls_12_381_precompiles` test.
- Please leave the issue numbers or links related to this PR …
=> tests: organize skipping state tests for EEST

tests/block_test_util.go
There were changes about IntrinsicGas in da652628cfacd052cac307b56ea43f9a583489a8, so I adopt tests/block_test_util.go to it.
- Remove `dataTokens` from the return value of `IntrinsicGas`
- Remove `dataTokens` from `NewMessage`'s argument.
=> fix: Adapt to changes in da652628cfacd052cac307b56ea43f9a583489a8

tests/block_test.go, tests/state_test.go
This PR adds the comments of  why we can skip old forks in EEST
=> tests: add comments of why we can skip old forks in EEST

cmd/kbn/main.go, cmd/utils/config.go, cmd/utils/flags.go, cmd/utils/nodeflags.go, networks/p2p/discover/table.go, networks/p2p/discover/udp.go, networks/p2p/server.go
- This PR adds `--discover-types` flag to enable discovery for specified node types only.
- Supported discovery types for each NodeType:
- CN: CN
- PN: PN, EN
- EN: PN, EN
- Note that BN is automatically enabled for all node types, and BNs have all node types enabled too.
- This PR is to fix PN-EN connection issue, so it should:
- not break current PN's static-driven connection structure, even after PNs are restarted
- make sure BNs bond with PNs (PNs report themselves to BNs)
- make sure ENs bond with PNs (ENs can discover and bond PNs)
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …
=> p2p: Add discover-types flag

api/tx_args.go, blockchain/types/transaction.go, blockchain/types/tx_internal_data_ethereum_set_code.go, snapshot/conversion.go, snapshot/generate.go, tests/block_test.go, tests/block_test_util.go, tests/state_test_util.go
As mentioned in #238, we will enable the EEST blockchain test that we skipped.
- Enable 7702 tests and 2537 tests (Except for calls to system contracts and type3)
- There were some issues with the 7702, so this will fix them.
- Prepared a simulation function for genesis.
- If there was an empty account in genesis, `useEthStateRoot` deleted it.
- Changing cast from SCA to ProgramAccount in snapshot.
- After the introduction of 7702, if genesis contained EOAwithStorage, this was not recorded in the snap.
- Allow set code tx to send to the zero address.
- The validation of set code tx prohibited calls to the zero address.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
=> tests: organize skipping blockchain tests for EEST

node/cn/backend.go
- The gov module was init twice and it leads `deriveSha` package to use different `headerGovModule`. So the the other logics(such as insertChain) and deriveSha package references different `headergov.History` and it causes the unexpected stop at apply block of deriveSha vote (apply block is a block one epoch past from governance block).
If this is a relatively large or complex change, kick off the discussion by explaining …
=> kaiax: fix duplicated init of gov module

blockchain/types/transaction.go, blockchain/types/transaction_test.go, kaiax/builder/bundle.go, kaiax/builder/bundle_test.go, kaiax/builder/impl/api.go, kaiax/builder/impl/errors.go, kaiax/builder/impl/getter.go, kaiax/builder/impl/getter_test.go, kaiax/builder/impl/init.go, kaiax/builder/interface.go, kaiax/gasless/impl/getter.go, kaiax/gasless/interface.go, kaiax/gasless/mock/module.go, log/log_modules.go
Implement skeleton of [KIP-245](https://kips.kaia.io/kips/kip-245).
Because the result can contain TxGenerator, the return type of `IncorporateBundleTx` is `[]interface{}`.
=> kaiax/builder: Add module skeleton

accounts/abi/bind/bind_test.go, api/api_public_transaction_pool_test.go, blockchain/tx_pool_test.go
`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.  More detail about TempDir  https://pkg.go.dev/testing#B.TempDir
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
=> refactor: use t.TempDir() instead of os.MkdirTemp

kaiax/builder/impl/getter.go, tests/kaia_scenario_test.go, tests/kaia_test_account_map_test.go, tests/kaia_test_blockchain_test.go, work/worker.go
- Add a test for the success of a bundle containing a tx generator and for evm error revert.
- Change the arg txs of ExtractBundlesAndIncorporate from TransactionsByPriceAndNonce to []*Transaction
- []*Transaction is the more commonly used type and is more convenient
- AccountMap.Update should now follow state changes made by TxGenerator
- To simulate tx, the nonce given to generate is set to zero.
- This does not affect subsequent operations on the AccountMap state.
- Please leave the …
=> tests: Add a test for the success of a bundle containing a tx generator and for evm error revert.

accounts/abi/bind/backends/blockchain_test.go, blockchain/tx_pool.go, blockchain/tx_pool_test.go, kaiax/gasless/impl/builder.go, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/helper_test.go, kaiax/gasless/impl/init.go, kaiax/gasless/impl/tx_pool.go, kaiax/gasless/impl/tx_pool_test.go, kaiax/gasless/mock/module.go, kaiax/interface.go, node/cn/backend.go, node/cn/gasprice/gasprice_test.go, node/sc/mainbridge_test.go, tests/account_keytype_test.go, tests/addtx_test.go, tests/kaia_test.go, tests/kaia_test_blockchain_test.go, tests/pregenerated_data_util_test.go, tests/transaction_test.go, tests/transaction_validation_test.go, tests/tx_cancel_test.go, tests/tx_fee_ratio_range_test.go, tests/tx_validation_test.go, work/mocks/txpool_mock.go, work/work.go
There are two instances of gasless module as TxPoolMoudule and TxBundlingModule. However, TxBundlingModule's one doesn't call tx pool's reset so state db has never been set. This PR fixes this.
- Make two gasless modules instances one
- Register transaction pool modules by `RegisterTxPoolModule` after initializing transaction pool
Moreover, updating statedb is a little complicated so this changes the way to pass statedb to setting pool field in moduels. This also change the way to get sender address from a transaction.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
=> kaiax/gasless: unify multiple gasless module instances

work/worker.go
Currently, there is a possibility that the bloom calculation may be incorrect and a bad block may be generated.
This is because `SetTxContext` is not executed for every tx that is executed.
This PR solves the problem by executing `SetTxContext` for each tx even when the execution target is a bundle.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
=> kaiax/gasless: execute SetTxContext for each tx

kerrors/kerrors.go, work/worker.go
This PR fix following bugs in Task.ApplyTransactions.
- `env.tcount` used in `SetTxContext` within `commitBundleTransaction` is not being incremented.
- `numTxsChecked` does not increment correctly for bundles.
- When the return value of `bc.ApplyTransaction` is `err == nil && receipt.Status != ReceiptStatusSuccessful`, `ShiftTxs` is executed instead of `PopTxs`.
If this is a relatively large or complex change, kick off the …
=> kaiax/gasless: fix some bugs in Task.ApplyTransactions

kaiax/builder/bundle.go, kaiax/builder/bundle_test.go, kaiax/builder/impl/getter.go, kaiax/builder/impl/getter_test.go, kaiax/builder/interface.go, kaiax/builder/tx_or_gen.go, kaiax/builder/tx_or_gen_test.go, kaiax/gasless/impl/builder.go, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/helper_test.go, tests/kaia_scenario_test.go, tests/kaia_test_account_map_test.go, work/worker.go
- Now gasless module initializes TxGenerator hash with `ApproveTx.Hash || SwapTx.Hash`. Previously, hash was initialized at `incorporate` lazily, which resulted in TxGenerators having incorrect hashes. TxGenerator's type is reverted back to function.
- Introduce `TxOrGen`; it replaces `[]interfaces{}` array from builder. `txOrGen` can be evaluated to tx by `GetTx(nonce)`.
- Change `Has(hash common.Hash)` -> `Has(txOrGen *TxOrGen)`. To find by hash, `FindIdx(id common.Hash)` can be used.
- Lambda functions are introduced in worker, such as `markAllTxUnexecutable`.
- Fix `tests/kaia_test_account_map_test.go` so txOrGen is evaluated to tx in the correct order.
=> kaiax/builder: Introduce TxOrGen

kaiax/gasless/impl/api.go, kaiax/gasless/impl/api_test.go, kaiax/gasless/impl/errors.go, kaiax/gasless/impl/getter.go, node/cn/backend.go
With the current gasless transaction, if you send an invalid tx using kaia_sendRawTransactions, no error is returned (the transaction receipt remains nil). So, the sender cannot know what the problem is.
Therefore, I added IsGaslessTx as an API for debugging.
=> Add isGaslessTx API

kerrors/kerrors.go, work/worker.go
This PR fixes the nil pointer panic due to accessing an empty transaction. Now `commitBundleTransactions` also explicitly returns nil for clarity.
=> Return custom error to avoid nil pointer panic

kaiax/auction/impl/api.go, kaiax/auction/impl/api_test.go
Changed to `hexutil.Big` for `Bid` type, Thank you @hyeonLewis.
=> api: Fixed RPC input type

kaiax/gasless/config.go, kaiax/gasless/impl/api.go, kaiax/gasless/impl/api_test.go, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/execution.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/init.go, kaiax/gasless/impl/tx_pool_test.go
This PR handle the following items:
- fix cn config initialization to set nil to allowedTokens
- use correct MultiCallContractCaller
- add gasless info api `debug_gaslessInfo`
- use backend statedb in tests
=> kaiax/gasless: fix gasless initialization, add gasless info api

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/contracts/testing/system_contracts/gasless/MockZeroPairFactory.sol, contracts/test/Gasless/ga.test.ts
- I verified the validity of the pair when adding the token and checked the liquidity.
- I have also fixed some tests as a result.
=> Check pair validity when adding tokens, and check liquidity

.circleci/config.yml
- Increase the [`resource_class`](https://circleci.com/docs/configuration-reference/#resourceclass) of `test-tests` job from medium (2core 4GB) to medium+ (3core 6GB) in an attempt to eliminate the intermittent CI failure.
=> ci: Increase executor size of test-tests

.circleci/config.yml, blockchain/system/auction.go, blockchain/system/auction_test.go, kaiax/auction/impl/api_test.go, kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/bid_pool_test.go, kaiax/auction/impl/builder.go, kaiax/auction/impl/builder_test.go, kaiax/auction/impl/execution_test.go, kaiax/auction/impl/getter.go, kaiax/auction/impl/getter_test.go, kaiax/auction/impl/handler_test.go, kaiax/auction/impl/init.go, kaiax/builder/bundle.go, kaiax/builder/bundle_test.go, kaiax/builder/impl/getter.go, kaiax/builder/impl/getter_test.go, kaiax/gasless/impl/builder.go, kaiax/gasless/impl/builder_test.go, node/cn/backend.go, work/worker.go
After merging this PR, the bid bundle will be mined if extracted.
We explicitly do not consider the empty bundle (see `#ExtractBundlesAndIncorporate`)
The auction module requires the additional boolean field in bundle: `TargetRequired`. If it's set to `true`, the bundle will be executed only when both conditions `I) it's next to target, ii) target has been executed successfully` are met (see `#shouldDiscardBundle, IsConflict`).
After extracting bundles from each module, it cooperates bundles by target tx (see `#CoordinateTargetTxHash`). It changes the order of bundles and makes them "linked" by updating the target tx hash to the last tx id of the prior bundle.
Now, the bundle is considered to be removed if target has been popped and `TargetRequired == true` (see `#FindDependentBundleIdx`) …
=> kaiax/auction: implement bid bundling

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/contracts/system_contracts/kip247/IKIP247.sol, contracts/test/Gasless/ga.test.ts
- I added deadline parameter to `swapForGas()`.
There is validation for deadline in swapExactTokensForETH, 
https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L19
but if you pass this as a fixed value, it will always pass when executing tx. Therefore, it is meaningless in the current implementation.This is a value that should be set by the user.
If this is a relatively large or complex …
=> fix: add a block num parameter

blockchain/tx_pool.go, cmd/homi/setup/cmd.go, cmd/utils/config.go, cmd/utils/nodeflags.go, kaiax/builder/impl/errors.go, kaiax/builder/impl/getter.go, kaiax/builder/impl/getter_test.go, kaiax/builder/impl/init.go, kaiax/builder/impl/tx_pool_wrapping.go, kaiax/builder/impl/tx_pool_wrapping_test.go, kaiax/builder/interface.go, kaiax/builder/mock/module.go, kaiax/builder/mock/tx_bundling_module.go, kaiax/gasless/config.go, kaiax/gasless/impl/api.go, kaiax/gasless/impl/builder.go, kaiax/gasless/impl/helper_test.go, kaiax/gasless/impl/tx_pool.go, kaiax/gasless/impl/tx_pool_test.go, kaiax/gasless/mock/module.go, kaiax/interface.go, kaiax/mock/tx_pool_for_caller.go, kaiax/mock/tx_pool_module.go, node/cn/backend.go, node/cn/config.go, work/mocks/txpool_mock.go, work/work.go
This PR mitigates overflow of invalid gasless transactions.
Even if users don't have any tokens, their gasless transactions can be promoted to pending. If they send a lot of such transactions, empty blocks keep to be created because users can set huge amount of gas price and invalid gasless transactions can occupy the head of TransactionsByPriceAndNonce.
All nodes limit the number of bundle txs in the pending. In the gasless module, this max number is 100 as default.
Let's take 3 as the max number for example about `IsReady(txs, next, ready)`, where bundle txs pair (An, Bn).
- `A1` will be promoted if `knownTxs: (), txs: (1: A1, 2: B1), next: 1, ready: ()`.
- `B1` will be promoted if `knownTxs: (A1), txs:(1: A1, 2: B1), next: 2, ready: (A1)`.
- `A2` will be rejected if `knownTxs: (A1, …
=> kaiax/builder: limit the number of bundle transactions in pending

client/kaia_client.go, kaiax/auction/impl/api.go, node/cn/filters/api.go
This PR enables the subscribe_log method in the auction namespace.
=> kaiax/auction: Enable subscribe_log in auction namespace

.circleci/config.yml
- This PR updates the version of `test-executor`'s docker image. It fixes the nightly-rpc failure.
Tested through next script
```
circleci local execute test-rpc
circleci local execute test-networks
```
=> circleci: update the version of test-executor docker image

blockchain/tx_pool.go, blockchain/tx_pool_test.go, tests/tx_validation_test.go
Add Prague validation in txpool for TxTypeEthereumSetCode, which must be rejected before Prague activation
=> txpool: add prague validation in txpool for TxTypeEthereumSetCode

blockchain/state_transition.go, blockchain/state_transition_test.go
For wide adoption of calling `AddAddressToAccessList`
* Remove the condition of `TxTypeEthereumSetCode` for `AddAddressToAccessList`
* Add the condition of `msgTo != nil` to call `AddAddressToAccessList` except `ContractCreation`
=> state: remove the condition of tx type for AddAddressToAccessList

kaiax/auction/impl/builder.go
[Nit] Minor change to the tx filter function: replaced the condition `tx + 150ms > now` with the more intuitive equivalent `tx > now - 150ms`, which clearly expresses the intent of filtering out txs that arrived more than 150ms ago.
=> kaiax/auction: rewrite ED comparison

node/cn/peer.go
We missed out to initialize bid cache in the function `newPeerWithRWs()`. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1908958]
goroutine 1106 [running]:
kaia/node/cn.(*basePeer).KnowsBid(...)
cn/peer.go:802
kaia/node/cn.(*peerSet).CNWithoutBid(0xc00141b860, {0x79, 0x29, 0x40, 0xe7, 0x2a, 0x4a, 0x1b, 0x95, 0x48, ...})
cn/peer_set.go:321 +0x1aa
kaia/node/cn.(*ProtocolManager).BroadcastBid(0xc0179c2000, 0xc00e3020c0)
cn/handler.go:1366 +0x67
kaia/node/cn.(*ProtocolManager).bidBroadcastLoop(0xc0179c2000)
cn/handler.go:1525 +0x28
created by kaia/node/cn.(*ProtocolManager).Start in goroutine 1
cn/handler.go:418 +0x25f
```
_Put an x in the boxes …
=> kaiax/auction: Added missing bid cache init

kaiax/gov/headergov/impl/consensus.go, kaiax/gov/headergov/impl/init.go, kaiax/gov/headergov/impl/init_test.go
- kaiax/gov will validate the header.voteData's validator field (the voter address) equals the block's proposer. Prevents a validator forging a header governance vote.
=> kaiax/gov: Check vote data against block proposer

kaiax/gov/headergov/impl/init.go, kaiax/valset/impl/getter_council.go, kaiax/valset/impl/getter_proposers.go, kaiax/valset/impl/init.go, tests/kaia_test_blockchain_test.go
- Use Snapshot of the `lowestScannedVoteNum` block to prevent bad block during the migration due to empty istanbul snapshot if no vote between (lowestScannedVoteNum, snapshot)
- Throttle migration threads (valset, gov)
- Add in-memory council cache (valset) to speed up syncing during migration. …
=> kaiax/valset,gov: improve migration threads

consensus/consensus.go, consensus/istanbul/backend/engine.go, datasync/chaindatafetcher/kafka/repository.go
- Since kaia hardfork, `getBlockWithConsensusInfo` returns `missing trie node` error when state is unavailable. However, except originProposer and committee, the other information is still available even state is unavailable. So this PR modifies the getBlockWithConsensusInfo API to return null originProposer and Committee when state is unavailable.
If this is a relatively large or complex change, kick off the discussion by …
=> istanbul/backend: return null OriginProposer when state not available at ConsensusInfo

.circleci/config.yml, blockchain/chain_makers.go, blockchain/error.go, blockchain/state_transition.go, blockchain/vm/eips.go, build/checksums.txt, build/ci.go, tests/block_test.go, tests/block_test_util.go, tests/state_test.go, tests/state_test_util.go
See: ethereum/go-ethereum/pull/31880
> We deleted outdated pectra-devnet-6@v1.0.0 release by mistake, so this PR updates the referenced EEST release to the correct latest version.
And I'd like to change **test-tests-executor** `resourece_class` to _**xlarge**_ in this time since I met the below even if I use large
> signal: killed
> CPU/Memory usage 100%
* https://app.circleci.com/pipelines/github/kaiachain/kaia/2966/workflows/77da5ed3-7a4a-4a5f-9849-d0fec2b59db2/jobs/16385/resources
_Put an x in the boxes that apply. You can also fill these out after creating …
=> build/EEST: update EEST to v4.5.0

console/web3ext/web3ext.go
This PR updates web3ext to match with v2.0.0 api changes.
- kaia_sendRawTransactions
- kaia_isConsoleLogEnabled
- debug_isGaslessTx
- debug_gaslessInfo
Test
env: local private network
```
curl -L 'http://localhost:8555/' -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"method": "kaia_sendRawTransactions","id": 1,"jsonrpc": "2.0","params": [["0xf8680185066720b30083015f909477d3cbbb706da786b2b5c54a5259fcbda0332a4980808308f0a6a0f3d8f142eaabd57996aa7b84fbb0229e623d501a573b4bef4559c03e0f1dfb7ca01dca4171aca043bb38c695034d36e1de51e7a5c1be9335fabfee7c79e5d8eb9b", "0xf8680285066720b30083015f909477d3cbbb706da786b2b5c54a5259fcbda0332a4980808308f0a5a0a618bb87b1b85b729868184aec1f4932b61e854ee708a131d533a1d5d1887a02a07a002bda5cde5bea6cfbce46bae4e62e29b9723b22d78157db86e101bac5e86e" …
```
=> console: update web3ext to match with v2.0.0 api changes

blockchain/tx_list.go, blockchain/tx_pool.go
Change behavior when the TxPool capacity is exceeded (from the LegacyPool of Geth)
- ASIS: Simple FixedSelection by size
- https://github.com/kaiachain/kaia/pull/391/files#diff-4a20f160f5182ec35d76a3566352906f577b84fbf3b242b922c4d2fc9c219cd7L1386-L1388
- TOBE: FixedPriorityQueue by gas price
- Don't accept by lower price
- https://github.com/kaiachain/kaia/pull/391/files#diff-4a20f160f5182ec35d76a3566352906f577b84fbf3b242b922c4d2fc9c219cd7R1050-R1055
- Kick out by other higher price
- https://github.com/kaiachain/kaia/pull/391/files#diff-4a20f160f5182ec35d76a3566352906f577b84fbf3b242b922c4d2fc9c219cd7R1096-R1103
- And when it happens to have too many kicks out, which is reorg, it also raises an error
- https://github.com/kaiachain/kaia/pull/391/files#diff-4a20f160f5182ec35d76a3566352906f57 …
=> txpool: Accept transaction from new sender with better price

common/bitutil/bitutil.go, common/fdlimit/fdlimit_darwin.go, common/hexutil/hexutil.go, common/hexutil/json.go, crypto/sha3/sha3.go, networks/p2p/msgrate/msgrate.go, networks/p2p/netutil/net.go, rlp/decode.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor: use the built-in max/min to simplify the code

consensus/istanbul/backend.go, consensus/istanbul/backend/backend.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler_test.go, consensus/istanbul/mocks/backend_mock.go
This PR fixed the log with the wrong proposer address when RC happened. It happened since the `currentCommittee` hasn't been updated, but it used it as a new round's state.
And it seems that the issue existed before the v2.0.0 refactoring https://github.com/kaiachain/kaia/blob/v1.0.3/consensus/istanbul/core/core.go#L304-L316
One possible caveat is that the current behavior of RC can be changed if the `GetProposerByRound` fails.
Before the patch
```
[RC] Catch up round                       address=0x70997970C51812dc3A010C7d01b50e0d17dc79C8 old_round=0 old_seq=79 old_proposer=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 new_round=1 new_seq=79 new_proposer=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
> kaia.getBlockWithConsensusInfo(79).originProposer …
```
=> Fix rc log to print correct new proposer

crypto/kzg4844/kzg4844.go, crypto/kzg4844/kzg4844_ckzg_nocgo.go, crypto/kzg4844/kzg4844_gokzg.go, crypto/kzg4844/kzg4844_test.go, go.mod, go.sum
- I am using the go-ethereum package, 
and go-ethereum uses go-kzg-4844 v1.1.0, while kaia uses go-kzg-4844 v0.7.0. 
I submitted a PR to align the versions.
- When using Blob, passing it by reference instead of by value improved memory usage.
- https://github.com/kaiachain/kaia/issues/414
...
=> Update go-kzg-4844 package to v1.1.0

kaiax/builder/impl/init.go, kaiax/builder/impl/tx_pool_wrapping.go
This request adds the following metrics:
- Number of knownTxs
- ![2025-06-13 12 19 32](https://github.com/user-attachments/assets/0b4d3384-f23a-41b4-a7a0-7b3b3af6aef7)
- The time of the oldest knownTx in knownTxs
- ![2025-06-13 12 19 57](https://github.com/user-attachments/assets/06d0ff76-504c-47f8-b8ab-506790fe7525)
These updates occur immediately after additions and deletions to knownTxs.
If this is a relatively large or …
=> kaiax/builder: Add metrics for knownTxs

consensus/istanbul/backend/handler.go
- This PR fixes the ValidatorPeerType to get the correct validator set which is the next block's validator set.
=> istanbul/backend: get next validator set at ValidatorPeerType

go.mod, go.sum
- Bump blst pacakge (the BLS12-381 library) v0.3.11 -> v0.3.14.
- v0.3.11 is compatible with `go1.23`, and we're using `go1.23.7`. So no problem so far.
- But it will break from the next `go1.24`. We're already seeing it in CodeQL runs, where `go1.24.4` is used. https://github.com/kaiachain/kaia/actions/runs/15599152362/job/43935784504
- See
- https://github.com/supranational/blst/issues/245
- https://github.com/supranational/blst/releases/tag/v0.3.14
- Please leave the issue numbers or …
=> Update supranational/blst to v0.3.14

.circleci/config.yml
- This PR fixes the deploy-rpm-public filter's regexp.
=> build: deploy-rpm-public filter regexp fix

kaiax/builder/impl/tx_pool_wrapping.go
This PR changes a log level of on exceeding max bundle tx num.
=> txpool: Change a log level on exceeding max bundle tx num

blockchain/tx_pool.go, kaiax/gasless/impl/execution.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/helper_test.go, kaiax/gasless/impl/init.go, kaiax/gasless/impl/tx_pool.go, kaiax/gasless/impl/tx_pool_test.go, kaiax/interface.go, kaiax/mock/tx_pool_for_caller.go, work/mocks/txpool_mock.go, work/work.go
- The kaiax/gasless module uses its own statedb `g.currentState` to query accounts.
- Previously, the module has been borrowing the txpool's `pool.currentState` variable without proper synchronization. There was a race condition hazard when accessing the statedb variable, and the values within.
- The `pool.currentState` is updated at `pool.reset()` which is triggered by ChainHeadEvent. The `g.currentState` is updated at `PostInsertBlock` which is also triggered after block insertion. These two are essentially updated at the same time, so this PR keeps the semantics.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …
=> kaiax/gasless: Use separate read-only state

api/api_ethereum.go, api/api_ethereum_test.go, api/api_public_blockchain.go, api/api_public_blockchain_test.go, blockchain/state_transition.go
- [KIP-223](https://github.com/kaiachain/kips/blob/main/KIPs/kip-223.md) brought [EIP-7623](https://eips.ethereum.org/EIPS/eip-7623) to Kaia
- However our gas estimation logic is behind sync, and we experienced gas estimation not correctly calculating required gas for long calldata
- `DoEstimateGas` only checks if its current attempt failed with `ErrInstrinsicGas` to try with a higher gas
- When the floor data gas was hit, `DoEstimateGas` returned `ErrFloorDataGas` instead of trying with a higher gas
- Handle (or bail out) for `ErrFloorDataGas` too, like we bail out on `ErrInstrinsicGas`
- Thanks to @ian0371  for the test updates
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
=> blockchain: Handle `ErrFloorDataGas` in `DoEstimateGas` for EIP-7623

work/worker.go
Pulling events via subscription is a common way in EVM-compatible chains, including Kaia.
All events occurred in a block must be in order.
- Ordering in a single transaction (events)
- Ordered during EVM execution (https://github.com/kaiachain/kaia/blob/dev/blockchain/state/statedb.go#L202, https://github.com/kaiachain/kaia/blob/891ffd6ee8d3b486e8cf8472b33b38e8575c71de/blockchain/vm/instructions.go#L889)
- Ordering in a block (transactions)
- Ordered during process (EN, PN) (https://github.com/kaiachain/kaia/blob/dev/blockchain/blockchain.go#L2127, https://github.com/kaiachain/kaia/blob/dev/blockchain/state_processor.go#L92)
However, when subscription is established with CN, the ordering is not guaranteed because of  (https://github.com/kaiachain/kaia/blob/dev/blockchain/state_processor.go …
=> worker: CN log subscription keeps the execution order

storage/database/rocksdb_database.go
This PR adds missing methods at rocksdb: 'Stat', 'Compact'.
Next rpc call helps to test the basic functionality: `debug.chaindbStat("rocksdb.stats")`, `debug.chaindbCompact()`
=> database: add missing methods at rocksdb

api/api_net.go, node/cn/backend.go
This PR is related to https://github.com/kaiachain/kaia/pull/444#discussion_r2189012234
- Move netAPI declaration to `APIs()` method to match other API patterns and remove the `netRPCService` struct field.
=> refactor(cn): consolidate netAPI initialization pattern

blockchain/blockchain.go
Previously, https://github.com/kaiachain/kaia/pull/437 PR adds txHash and blockHash when logging getReceiptsByTxHash failure, but it turns out it only shows abbreviated values. This PR fixes it to show full contents of txHash and blockHash.
AS-IS
```
txHash=b5c63d…cfe6d9 blockHash=60319d…29d41e
```
TO-BE
```
txHash=0xb5c63d449888f2d62222f660ba31510798f6823d4128ab8a55e60feae5cfe6d9 blockHash=0x60319dcac9c952052c6b8c7dc895671ae074b8f18c0fcc417ec6415ca829d41e
```
- Please leave the issue …
=> api: fix getReceiptByTxHash error message

kaiax/gasless/impl/api.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/init.go, kaiax/gasless/impl/tx_pool.go
Protect `g.swapRouter` and `g.allowedTokens` from concurrency. It can occur during the `PostInsertBlock`.
=> kaiax/gasless: Prevent concurrency at PostInsertBlock

kaiax/supply/impl/getter.go
Currently, `GetTotalSupply` caches the value regardless of error. 
The problematic flow can be:
1. First call: upstream works, so it returns the correct value. But the node already caches the wrong value.
2. Second call: Since the node has cached the "wrong" value, it returns the cached value -> doesn't trigger upstream logic.
```
// before
> kaia.getTotalSupply(10)
Error: cannot determine canonical (0x0, 0xdead) burn amount: missing trie node b0cfdd439f23eee870d59d8ca715c3f3b301b1fce3b060036e105fdc2f453e4f (path )
at web3.js:6814:9(39)
at send (web3.js:5225:62(29))
at <eval>:1:20(3)
> kaia.getTotalSupply(10)
{
burntFee: "0x0",
deadBurn: null,
kip103Burn: "0x0",
kip160Burn: "0x0",
number: "0xa",
totalBurnt: null,
totalMinted: "0x111b0ec57e6499a1f4b1014d3fc09d4835ec5800000",
totalSupply: …
```
=> kaiax/supply: Fix cache condition

kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/builder.go
This PR makes `GetTargetTxMap` to return copied map, not original map.
=> kaiax/auction: Fix auction concurrency issue

blockchain/evm.go
- This PR fixes potential overflow in `blockchain.DoEstimateGas` as reported in ethereum/go-ethereum#32255.
- ref: [Google Research Blog Post](https://research.google/blog/extra-extra-read-all-about-it-nearly-all-binary-searches-and-mergesorts-are-broken/)
I tried to add test case in `api/api_eth_test.go` for the overflow leading to misbehavior, however it was tricky.
- We could trigger overflow easily with very large `gaslimit` however the search could easily find out the correct value if …
=> blockchain: Fix potential overflow in `DoEstimateGas`

networks/p2p/rlpx/rlpx.go
- This PR optimizes `rlpx.xor` using `bitutil.XORBytes` according to ethereum/go-ethereum#32217
- Benchmark result:
```
BenchmarkManualXOR-10             789076              1510 ns/op
BenchmarkBitutilXORBytes-10      1762501               669.5 ns/op
```
- none
<details>
<summary>benchmark code</summary>
```
package yourpkg
import (
"math/rand"
"testing"
"github.com/ethereum/go-ethereum/common/bitutil"
)
var (
srcA = make([]byte, 1024)
srcB = make([]byte, 1024)
dst  = make([]byte, 1024)
) …
```
=> rlpx: Optimize xor using bitutil.XORBytes

accounts/abi/bind/bind.go
- This PR precompiles regex used in `accounts/abi/bind`
- Follw-up PR for ethereum/go-ethereum#32301
- none
none
=> abi/bind: Precompile regex

common/hexutil/hexutil.go, common/hexutil/json_test.go
- This PR replace custom calculated bit sizer with `bit.UintSize` as per ethereum/go-ethereum#32304
- none
none
=> common/hexutil: Use bit.UintSize instead of custom calculated size

node/cn/filters/api_kaia_filter.go, node/cn/filters/filter_system_test.go
- This PR brings ethereum/go-ethereum#31877
- The updates are:
- add check for filter API arguments having both `blockHash` and `fromBlock`/`toBlock` specified and returns error accordingly (those are mutually exclusive)
- existing test did not correctly check the returned error, so fix them …
=> node/cn/filters: Check filter GetLogs args correctly and add test cases

networks/rpc/types.go, networks/rpc/types_test.go
Support `safe` and `finalized` block number for API and they treat as the same as `latest` because of Kaia [BFT](https://docs.kaia.io/learn/)
NOTE:
* `rpc.BlockNumber` and `rpc.BlockNumberOrHash` cannot specify the negative value
* All API parameter depends on `rpc.BlockNumber`
* `rpc.BlockNumberOrHash` and `filters.FilterCriteria` also depends on `BlockNumber`
* But this PR don't change the magic number for Ethereum compatibility because of Kaia treat EarliestBlockNumber as the same as Genesis Block Number:
* Kaia: https://github.com/kaiachain/kaia/blob/0f2059e82b30198bce1276d28eedd5907c52d349/networks/rpc/types.go#L79-L81
* Geth: https://github.com/ethereum/go-ethereum/blob/792de5d2e3b40837aadb65993e387bf5aa5bce9f/rpc/types.go#L66-L70 …
=> types: Support "safe|finalized" alias for BlockNumber as the same as LatestBlockNumber

accounts/abi/error_handling.go, accounts/abi/pack.go, accounts/abi/pack_test.go, accounts/abi/type.go, accounts/abi/unpack.go, accounts/abi/unpack_test.go
This PR cherry-picks two upstream changes from go-ethereum to fix unsafe behavior when ABI-encoding values.
Specifically:
- #26568: Prevents packing of negative values into unsigned types (`uint`) during ABI encoding.
- #31790: Adds stricter input validation to avoid unintended encoding of negative values as large uints.
These changes improve the correctness and safety of contract interactions by eliminating edge cases that could result in invalid transaction data or runtime errors.
- …
=> abi: Fix ABI uint packing and negative value bug

blockchain/vm/analysis.go, blockchain/vm/contract.go, blockchain/vm/contracts_test.go, blockchain/vm/evm.go, blockchain/vm/instructions_test.go, blockchain/vm/jumpdests.go, blockchain/vm/logger_test.go, node/cn/tracers/tracer_test.go, tests/benchmarks/benchmarks_test_utils.go
- This PR makes jumpdest analysis cache to be configurable in EVM ([geth#32143](/ethereum/go-ethereum/pull/32143))
- It provides an abstraction for the cache, not a better implementation of the cache. However I got better benchmark result:
```
BenchmarkJumpdestAnalysisCache/CacheEnabled-10            432151              2460 ns/op         3389 B/op         43 allocs/op
BenchmarkJumpdestAnalysisCache/CacheEnabled-10            722662              1553 ns/op         2778 B/op         40 allocs/op
```
see below for more info on the benchmark.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what …
=> blockchain/vm: Add configurable jumpdest analysis cache

kaiax/gasless/impl/getter.go
- Stop the following log before Randao fork.
```
WARN[09/02,00:31:46 +09] [64] there is something wrong with multicall contract  err="abi: attempting to unmarshall an empty string while arguments are expected"
```
- c.f. https://github.com/kaiachain/kaia/blob/v2.0.3/kaiax/staking/impl/getter.go#L132
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
=> kaiax/gasless: Check Registry before calling Multicall

kaiax/auction/impl/api.go, kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/metric.go
- `auction_submitBid`
- Number of bid request metric is added.
- For subscription:
-   Use existing metrics: https://github.com/kaiachain/kaia/blob/dev/networks/rpc/metrics.go#L26-L28
- Number of websocket connections is managed by node configuration: https://github.com/kaiachain/kaia/blob/v2.1.0-rc.3/cmd/utils/flags.go#L956-L987
If this is a relatively large or complex change, kick off the discussion by explaining why you …
=> [Auction] Added bid request metric

api/api_kaia.go, datasync/downloader/api_kaia_downloader.go, node/cn/backend.go
Copy commits from https://github.com/kaiachain/kaia/pull/529 because its PR cannot pass the "ci/circleci: pass-testsExpected — Waiting for status to be reported"
This PR clarifies the eth_syncing and subscribe["syncing"] APIs by separating the implementation into distinct types while maintaining the same functionality.
- Add `EthDownloaderAPI` that wraps `KaiaDownloaderAPI` for eth namespace clarity
- Add API comparison comments in `KaiaDownloaderAPI.Syncing()` and `KaiaAPI.Syncing()` to document the differences between HTTP and WebSocket versions
- Maintain same functionality using pointer embedding to share the same instance
No functional changes - existing behavior is preserved
_Put an x in the boxes that apply. You can also fill …
=> feat: clarify eth_syncing and subscribe[syncing] APIs

api/api_kaia_blockchain.go
- This PR make `GetBlockWithConsensusInfoByNumber` to accept pending block.
- as-is:
```
> klay.getBlockWithConsensusInfo("pending")
Error: pending is not allowed
at web3.js:6814:9(39)
at send (web3.js:5225:62(29))
at <eval>:1:31(3)
``` 
- to-be: (note that `committee` is null and `committers` is empty)
```
> klay.getBlockWithConsensusInfo("pending")
{
baseFeePerGas: "0x5d21dba00",
blockScore: "0x1",
committee: null,
committers: [],
extraData: "0xd883020100846b6c617988676f312e32332e37856c696e757800000000000000d8d594b1e5a9c4a8bbaf241b2f9d8d60375c8cea9c27bc80c0",
gasUsed: "0x0",
governanceData: "0x",
hash: null,
logsBloom: "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> api: Allow pending block for `GetBlockWithConsensusInfoByNumber`

accounts/abi/bind/backends/blockchain_test.go, accounts/abi/bind/backends/simulated.go, api/api_eth_test.go, blockchain/bench_test.go, blockchain/block_validator_test.go, blockchain/blockchain_sethead_test.go, blockchain/blockchain_test.go, blockchain/chain_makers_test.go, blockchain/genesis_test.go, blockchain/state_migration_test.go, consensus/faker/faker.go, consensus/faker/faker_test.go, datasync/chaindatafetcher/kas/repository_test.go, datasync/downloader/downloader_test.go, datasync/downloader/queue_test.go, datasync/downloader/testchain_test.go, datasync/fetcher/fetcher_test.go, node/cn/api_backend_test.go, node/cn/filters/filter_system_test.go, node/cn/filters/filter_test.go, node/cn/gasprice/gasprice_test.go, node/cn/handler_test.go, node/cn/tracers/api_test.go, tests/block_test_util.go, work/remote_agent.go
- This PR introduces faker which is derived from gxhash. The consensus engine for tests are replaced to faker.
- In later PR, the gxhash and clique will be removed.
=> consensus: introduce faker and replace gxhash with faker

work/worker.go
Added a log when a bundle is skipped. Currently, it can only happen with the Auction module bundle.
=> worker: Add log when bundle skipped

contracts/contracts/system_contracts/auction/AuctionFeeVault.sol
For the validator payback, use `.call` with an additional 5000 gas to allow validators to register a Multisig wallet (e.g., Safe).
Currently, it requires 6329 gas for KaiaSafe to receive KAIA. So `2300 + 5000` will be sufficient for the KAIA payment. Please note that `.call` will add default `2300` gas when `value != 0`.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> contract: Use call for validator payback

go.mod, kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/handler.go, kaiax/auction/impl/handler_test.go, kaiax/auction/interface.go, kaiax/auction/mock/auction_module_mock.go, node/cn/handler.go, node/cn/handler_msg_test.go
This PR introduces a bid rate limiter for each peer. The bidpool records `peerID -> limiter` to keep track of bids from peer.
It also increases the bidMsg channel size from 100 to 2048.
=> kaiax/auction: Introduce bid rate limiter

contracts/contracts/system_contracts/auction/AuctionDepositVault.sol, contracts/contracts/system_contracts/auction/AuctionError.sol, contracts/test/Auction/auctionDepositVault.test.ts
This PR prevents underflow in the auction deposit vault getters.
=> contract: Prevent underflow in deposit vault getter

node/cn/filters/api_kaia_filter.go
Currently, the subscription hasn't been cleared when an error occurred in the filter APIs. This PR fixes `*Filter()` APIs to correctly unsubscribe the subscription.
=> api/filters: Unsubscribe sub at filter api

contracts/contracts/system_contracts/auction/AuctionEntryPoint.sol, contracts/test/Auction/auctionEntryPoint.test.ts, kaiax/auction/README.md, kaiax/auction/errors.go, kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/bid_pool_test.go
Similar to the tx size limit (128KB), introduce a bid data size limit to 64KB. It prevents consuming too much data gas and potential DoS.
Increase a `gasBufferEstimate` to `200,000` to secure an enough margin with intensive bid tx. It doesn't charge the actual bid and can be decreased after the stabilization.
```
// bid.Data = 4 bytes (only selector), callGasLimit = 3.5M (consume all gas internally)
> intinsicGas = 26684
> gasUsed = 3645813
> gasUsed - intrinsicGas - callGasLimit = 119,129 (<= gas buffer)
// bid.Data = 64KB, callGasLimit = 2M (consume all gas internally)
> intinsicGas = 1075320
> gasUsed = 4717666
> gasUsed - intrinsicGas - callGasLimit = 142,346 (<= gas buffer)
```
_Put an x in the boxes that apply. You can also fill …
=> kaiax/auction: Limit the bid data size to 64KB
