kaiachain/kaia

accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go
- `SimulatedBackend.SuggestGasPrice` is now based on the pending block, to return the next block's base fee * 2.
- Consistent with `BlockchainBackend.SuggestGasPrice` which is based on txPool.GasPrice() = NextMagmaBlockBaseFee
=> bind: SimulatedBackend.SuggestGasPrice is based on pending block

contracts/test/TreasuryRebalance/trv2.test.ts
Add test for `TreasuryRebalanceV2`. The branch coverage is 91%.
=> Add test for TreasuryRebalanceV2

contracts/docs/CnStakingV3.md
=> docs: Fix word

networks/rpc/endpoints.go, node/sc/mainbridge.go
Fix sc's mainbridge to register Kaia namespace.
This PR brings @blukat29's [hotfix](https://github.com/blukat29/klaytn/tree/hotfix/scn-to-klay-rpc)
=> Fix service chain rpc

node/cn/gasprice/gasprice.go, node/cn/gasprice/gasprice_test.go
Currently, `SuggestTipCap` always returns tip cap based on fee history. This PR makes it return zero tip cap if `nextBaseFee == LowerBoundBaseFee`, which is currently 25 Gkei.
```
// When nextBaseFee == 25 Gkei
> cast rpc eth_maxPriorityFeePerGas --rpc-url http://localhost:8551/   
> "0x0"
> cast rpc eth_gasPrice --rpc-url http://localhost:8551/                                                                  
> …
```
=> Return zero tip cap if next baseFee is lower bound

params/config.go, params/version.go
Tentative. Block numbers are subject to change.
=> Version v1.0.1, Mainnet Kaia and KIP160 hardfork configuration

.circleci/config.yml
- Follow-up of #37
Failed job: https://app.circleci.com/pipelines/github/kaiachain/kaia/120/workflows/158ff303-04d4-446a-958f-3babe7755aee
=> ci: Fix rpm-tagged-baobab

.circleci/config.yml
- In CircleCI's `test-rpc` job, run `apt upate` before running `apt install python3.8 ...`
- Failed run https://app.circleci.com/pipelines/github/kaiachain/kaia/218/workflows/feb59620-718a-4dd7-9ff3-531e474caa31/jobs/1243
```
The following NEW packages will be installed:
python3-venv python3.8-venv
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 6680 B of archives.
After this operation, 38.9 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.9
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 python3-venv amd64 3.8.2-0ubuntu2 [1228 B]
Err:1 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.9
404 …
```
=> ci: Fix circleci test-rpc apt install command

log/format.go, node/api.go, node/sc/api_bridge.go, snapshot/generate.go, tests/pregenerated_data_util_test.go
fix some comments
- [ x] Others
=> chore: fix some comments

.circleci/config.yml, build/package-tar.sh
- This PR enables darwin-arm64 build for packaging.
- Test run: https://app.circleci.com/pipelines/github/kaiachain/kaia/253
- Test output: https://packages.kaia.io/kaia/v1.0.1/ken-v1.0.1-0-darwin-arm64.tar.gz
=> ci: Enable darwin-arm64 build

.circleci/config.yml
- Update path for package and repo for test data
=> ci: update rpm packages and repo URLs

params/version.go
=> Set version to v1.0.2

api/api_public_klay.go, reward/supply_manager.go, reward/supply_manager_test.go, storage/database/db_manager.go, storage/database/db_manager_test.go, storage/database/schema.go
- Rename "AccReward" to "SupplyCheckpoint" and update comments, variables, functions accordingly.
- Add DeleteSupplyCheckpoint accessor.
- No semantic change.
=> database: Rename AccReward to SupplyCheckpoint

params/config.go
- Mainnet
- Kaia block number: [162900480](https://klaytnscope.com/blockCount/162900480) est. 2024-08-29 10:29 UTC+9
- Kip169 block number: same as above
=> params: Set Mainnet Kaia and KIP160 fork block number

tests/README.md
- This PR fixes the link of the `kaia-core-tests` repo described in the tests/README
=> Fix tests repo link for tests/README

params/bootnodes.go
- This PR updates bootnode URLs to `kaia.io` domain.
- Also removed CN and PN bootnodes, because CN bootnodes are set by node config and PN peers are set by `static-nodes.json` (we don't operate PN bootnode).
=> Tidy up bootnodes

contracts/docs/PublicDelegation.md
Update public delegation docs.
- Delete the misleading parts
- Update outdated info
- Fix typo
=> Update public delegation docs

reward/supply_manager.go
- SupplyManager does not panic when a header, block, or receipt is not found during the catchup.
=> reward: SupplyManager to not panic on missing blocks

params/version.go
=> Set version to v1.0.3

accounts/abi/bind/backends/blockchain.go, accounts/abi/bind/backends/simulated.go, api/api_ethereum.go, api/api_public_blockchain.go, api/tx_args.go, node/cn/tracers/api.go
The initial gas payment for the access list has not been paid. This change does not involve the HF since all of its modifications are involved with the getter, neither verification nor consensus.
@blukat29 Please consider this to be added v1.0.4 
=> [API] Added missing accesslist initial payment

cmd/homi/setup/cmd.go, cmd/homi/setup/flags.go, governance/api.go, params/config.go
Followed the previous process from:
- Cancun: https://github.com/klaytn/klaytn/pull/1969/files
- Kaia(Dragon): https://github.com/klaytn/klaytn/pull/2114/files
- Geth(Prague): https://github.com/ethereum/go-ethereum/pull/26481/files
Please let me know if anything is missing.
```shell
> kaia.getChainConfig()
{
...
...
istanbulCompatibleBlock: 0,
kaiaCompatibleBlock: 0,
kip103CompatibleBlock: 0,
kip103ContractAddress: "0x0000000000000000000000000000000000000000",
kip160CompatibleBlock: 0,
kip160ContractAddress: "0x0000000000000000000000000000000000000000",
koreCompatibleBlock: 0,
londonCompatibleBlock: 0,
magmaCompatibleBlock: 0,
pragueCompatibleBlock: 0,
randaoCompatibleBlock: 0,
shanghaiCompatibleBlock: 0,
}
```
_Put an x in the boxes …
=> params: Declare Prague hardfork configuration

kaiax/staking/impl/getter.go, kaiax/staking/impl/init.go, kaiax/staking/impl/preload_buffer.go, kaiax/staking/impl/side_state.go, kaiax/staking/interface.go, kaiax/staking/mock/staking.go, node/cn/backend.go, node/cn/state_accessor.go, reward/staking_manager.go, tests/state_reexec_test.go
- Add the "Preload" feature in the kaiax/staking. Serves the same purpose with the existing PreloadStakingInfo.
- Usage
```
mStaking.AllocPreloadRef() -> RefId
mStaking.PreloadFromState(RefId, StateDB)
mStaking.FreePreloadRef(RefId)
```
- Data structure
```
PreloadBuffer: [StateRoot] -> { StakingInfo, [RefId] -> struct{} }
Suppose there are two concurrent state reexec threads.
First thread is assigned RefId=1, and reexec through three blocks of which state roots are H1, H2, H3.
Second thread is assigned RefId=2, and reexec through three blocks of which state roots are H3, H4, H5.
The resulting SideStates looks like this:
H1 -> { S1, [1] }
H2 -> { S2, [1] }
H3 -> { S3, [1,2] }
H4 -> { S4, [2] }
H5 -> { S5, [2] }
```
- The GetStakingInfo() also refers to the PreloadBuffer.
The SideState …
=> kaiax/staking: Implement Preload feature

.circleci/config.yml
- Upgrade docker excutor due deprecated executor image:
https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
=> Update Docker excutor

blockchain/vm/operations_acl.go
Checks overflow condition at gas addition
=> core/vm: Added gas overflow check

networks/p2p/peer.go
Concurrent ping request handling is constrained 
The patch brought looks valid and should not harm any previous work. The unit test function `TestMultiChannelPeerPing()` in `peer_test.go` file  intermittently hangs.
I found the `SendItems()` makes hang. The localized hang location is https://github.com/kaiachain/kaia/blob/dev/networks/p2p/rlpx/rlpx.go#L266.  If I revert the patch, there's no intermittent hangs. Currently still identifying.
The code structure differs from Geth's: in our implementation, `pingLoop()`, `readLoop()`, and `handle()` each take an `rw` connection as a parameter, rather than relying on a structure member. This means a valid `rw` connection should be passed through the chain: `readLoop(rw) -> handle(rw) -> pingLoop(rw)`. Initially, I copied Geth’s code, where …
=> p2p: Restrict concurrent ping requests

accounts/abi/bind/backend.go, networks/p2p/server.go, node/cn/peer.go
fix some function names in interface comment
=> chore: fix some function names in interface comment

consensus/istanbul/backend/engine.go, kaiax/interface.go, node/cn/backend.go
This PR closes #138.
Temporary register mReward to consensus module to prevent invalid state root calculation at the node startup. It can't handle reward distribution at `FinalizeHeader` without mReward in consensus module.
```
INFO[11/25,09:12:35 +09] [41|node/cn/backend.go:388]                    Start creating istanbul snapshot
ERROR[11/25,09:12:35 +09] [44|reward/staking_manager.go:344]             incorrectly regenerated historical state  block=1 err="mistmatching state root block expected e1613dbd3f99020e6f96b5189b92e81dfd3bd0edce32d2cb9257e5a8200449ae reexecuted ace5112350806332ee435b9b98f8d594d8087f7aab17f8ef024353fb0632ac2f"
ERROR[11/25,09:12:35 +09] [41|node/cn/backend.go:499]                    Preload staking info failed               err="incorrectly regenerated historical …
```
=> Temporary register mReward to consensus

blockchain/types/transaction_test.go
Case 5, 6, and 7 weren't tested in `TestTransactionCoding` because `switch i % 5 ` can't be more than 4.
=> Fix `TestTransactionCoding` to test all cases

networks/p2p/discover/udp.go
=> p2p: findnode responds at most 2 PNs

kaiax/staking/impl/schema.go, kaiax/staking/impl/schema_test.go
- Fix `json.Unmarshal(nil)` bug.
=> kaiax/staking: Fix ReadStakingInfo nil

consensus/istanbul/backend.go
=> chore: fix problematic comment

.github/CODEOWNERS
- Remove Aidan from the CodeOwnerlist because I cannot use much of my time for development now. 
- Please add me as a review when my review is needed
=> Remove Aidan from CodeOwner

blockchain/blockchain_test.go
Add a test that executes EOA with code in execution type
- target types
- `TxTypeSmartContractExecution`
- `TxTypeFeeDelegatedSmartContractExecution`
- `TxTypeFeeDelegatedSmartContractExecutionWithRatio`
=> Add a test that executes EOA with code in execution type

tests/gen_sttransaction.go, tests/state_test.go, tests/state_test_util.go
This PR enables state tests for all old EIPs by Cancun and Prague forks.
related: #152
=> tests: Enable state tests for all old EIPs by Cancun and Prague forks

contracts/contracts/system_contracts/consensus/IVoting.sol, contracts/contracts/system_contracts/consensus/StakingTracker.sol, contracts/contracts/system_contracts/consensus/Voting.sol
- Voting and StakingTrackerV1 contracts are imported
- Test files will be imported in following PR with other contracts(StakingTrackerV2, multicall, CLRegistry)
=> contracts: Add Voting and StakingTrackerV1 contracts

contracts/contracts/system_contracts/consensus/CLRegistry/CLRegistry.sol, contracts/contracts/system_contracts/consensus/CLRegistry/ICLRegistry.sol, contracts/contracts/system_contracts/consensus/MultiCallContract.sol, contracts/contracts/system_contracts/consensus/StakingTrackerV2/IStakingTrackerV2.sol, contracts/contracts/system_contracts/consensus/StakingTrackerV2/StakingTrackerV2.sol, contracts/test/CLRegistry/clregistry.test.ts, contracts/test/StakingTrackerV2/compatibility.test.ts, contracts/test/StakingTrackerV2/stakingTrackerV2.test.ts, contracts/test/common/fixtures.ts, contracts/test/common/helper.ts, contracts/test/stakingTracker.test.ts, contracts/test/voting.test.ts
- MultiCall, CLRegistry, and StakingTrackerV2 contracts are imported
- Corresponding test files are imported including (StakingTrackerV1 and Voting)
=> contracts: Import MultiCall, CLRegistry, StakingTrackerV2 contracts

contracts/hardhat.config.ts
Since the `credit` related contracts exceed max size, we need to manually disable/delete those contracts before running compiling or tests. Since these contracts are immutable and rarely need to be compiled (especially no need via hardhat), excluding them from source path would be useful. …
=> Filter credit contract related paths

.circleci/config.yml
- Update yum path to stream9
- Update golang in circleCI
=> ci: upgrade rpm golang to 1.23.3

kaiax/gov/impl/api.go
Add missing prague field for `kaia_getChainConfig()`.
=> Add missing prague HF config

blockchain/types/account/account.go, blockchain/types/account/account_common.go, blockchain/types/account/account_test.go, blockchain/types/account/externally_owned_account.go, blockchain/types/account/legacy_account.go, blockchain/types/account/smart_contract_account.go
Remove redundant or test purpose methods for account type. Moved `Equal` to testing file.
=> Remove test purpose method in account type

params/version.go
- Set version to v2.0.0.
- Incrementing the Major version because this it contains a governance&tokenomics-related hardfork, namely Consensus Liquidity.
=> params: Set version to v2.0.0

cmd/homi/setup/flags.go
=> Update homi base image to kaia

.circleci/config.yml, build/Dockerfile-go1.23.3-rpmbuild-gcc7, build/Dockerfile-go1.23.3-rpmbuild-gcc7-arm, build/Dockerfile-go1.23.3-solc0.8.13-ubuntu-22.04-arm, build/package-rpm.sh, build/rpm/main.go
- Fix aws-cli install in ARM
- Fix gdb-add-index not found issue when building rpm package (add gdb and which in centos 9)
- Fix debugsourcefiles.list not found when building rpm package (add %global debug_package %{nil} to spec file rpm)
=> build: fix build base images

node/cn/api_backend.go
=> api: Hash format string fixed

blockchain/state/statedb.go, tests/block_test_util.go
=> Enable check storage

tests/block_test.go, tests/block_test_util.go
=> Enable old forks for blockchain EEST

test.txt, tests/block_test.go
=> Reset global variables for gxhash

test.txt
=> Remove unused file

consensus/gxhash/consensus.go, tests/block_test.go, tests/block_test_util.go
=> Remove a gxhash global variable

tests/block_test_util.go
=> Set reward by Finalize

.github/workflows/CodeQL.yml
Upgrade CodeQL to v3 because its v2 is deprecated
https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
=> upgrade: Update CodeQL.yml

node/cn/backend.go
Register `mStaking` to blockchain execution module.
=> kaiax/staking: Register mStaking to blockchain execution module

.github/workflows/CodeQL.yml
Update on push codeql check in dev branch
=> update codeql check in dev branch

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/contracts/system_contracts/kip247/IKIP247.sol, contracts/contracts/system_contracts/kip247/IWKAIA.sol, contracts/contracts/testing/system_contracts/WKAIA.sol, contracts/contracts/testing/system_contracts/gasless/MaliciousReceiver.sol, contracts/contracts/testing/system_contracts/gasless/MaliciousToken.sol, contracts/contracts/testing/system_contracts/gasless/MaliciousWKAIA.sol, contracts/contracts/testing/system_contracts/gasless/MockCoinbase.sol, contracts/contracts/testing/system_contracts/gasless/MockInvalidFactory.sol, contracts/contracts/testing/system_contracts/gasless/TestToken.sol, contracts/hardhat.config.ts, contracts/package-lock.json, contracts/package.json, contracts/test/Gasless/ga.test.ts, contracts/test/materials/fixtures/gaslessSwapRouter.ts, contracts/test/materials/index.ts
Add GaslessSwapRouter contract and unit tests for KIP-247
=> feat: Add GaslessSwapRouter contract

node/cn/tracers/internal/tracers/assets.go
Since we have already checked err before and returned != nil, err must be nil here. In fact, it should return clErr.
=> fix: fix incorrect nil return value

blockchain/tx_list.go, blockchain/tx_pool.go, blockchain/tx_pool_test.go, blockchain/types/transaction.go
Validate “SetCodeAuthentication.Authorities” in `txpool`
1. Accounts with delegation set can only have one in-flight transaction.
2. Setcode tx should be rejected if any authority has a known pooled tx.
3. New txs from senders with pooled delegations should not be accepted.
4. Ensure setcode tx can replace itself provided the fee bump is enough.
5. Make sure that if a setcode tx is replaced, the auths associated with
the tx are removed.
5.1. This should also work when a self-sponsored setcode tx attempts
to replace itself.
6. Verify nonces in setcode tx are at least valid when initially added to
the pool, otherwise someone might submit old validations to deny
service to unsuspecting users.
Changes:
* Implement `validateAuth` in `TxPool` for above validations 
* Implement …
=> blockchain/txpool: improve validation of Authorities(EIP-7702: SetCodeTx)

tests/kaia_scenario_test.go, tests/kaia_test.go, tests/pregenerated_data_generation_test.go, tests/pregenerated_data_util_test.go
make function comment match function name
=> chore: make function comment match function name

blockchain/state/statedb.go, blockchain/state/statedb_test.go
Make `statedb.Copy` copy the dirty storage together.
=> statedb: Copy dirty storage

kaiax/gasless/impl/builder.go, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/helper_test.go, kaiax/gasless/impl/tx_pool_test.go
This PR adds additional tests for kaiax/gasless. And this also adds conflict checking against bundles made by itself.
=> kaiax/gasless: add additional tests

consensus/istanbul/backend/handler.go, consensus/protocol.go, datasync/downloader/peer.go, node/cn/backend.go, node/cn/channel_manager.go, node/cn/handler.go, node/cn/handler_msg_test.go, node/cn/peer.go, node/cn/peer_mock_test.go, node/cn/peer_set.go, node/cn/peer_set_mock_test.go, node/cn/protocol.go, node/cn/protocolmanager_mock_test.go
It adds a new bid message type. It upgrades the protocol version to kaia/66.
=> kaiax/auction: handle remote bid

client/kaia_client.go, console/web3ext/web3ext.go, kaiax/auction/README.md, kaiax/auction/bid.go, kaiax/auction/errors.go, kaiax/auction/impl/api.go, kaiax/auction/impl/api_test.go, kaiax/auction/impl/bid_pool.go, kaiax/auction/impl/execution_test.go
API `auction_submitBid`  added.
```sh
curl -H "Content-Type: application/json" \
--data '{
"jsonrpc": "2.0",
"method": "auction_submitBid",
"params": [
{
"targetTxRaw": "0xf8674785066720b30083015f909496bd8e216c0d894c0486341288bf486d5686c5b601808207f4a0a97fa83b989a6d66acc942d1cbd70f548c21e24eefea12e72f8c27ba4369a434a01900811315ba3c64055e9778470f438128b54a46712cc032f25a1487e2144578",
"targetTxHash": "0xc7f1b27b0c69006738b17567a7127c4d163fac7b575d046c6cbc90e62e6355e8",
"blockNumber": 1,
"sender": "0x14791697260E4c9A71f18484C9f997B308e59325",
"to": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
"nonce": 4,
"bid": 3,
"callGasLimit": 2,
"data": "0x1234",
"searchersig": "0x2cd97ec3eb8230a8cac9169146ea6ca406d908edd488e5fda30811ebf56647d94740d582c592e3476481b3fbab38a100623d2f4b0615da8b8dfd0f99128879 …
```
=> kaiax/auction: bid submission API added

kaiax/auction/impl/api.go, node/cn/filters/api.go
Extract common function implementation and calls it at each namespace.
=> [API] FilterAPI refactored

kaiax/auction/impl/api.go
Can use globally defined property name in clitne side
=> kaiax/auction: RPC output property defined

node/cn/filters/api.go
@hyeonLewis Sorry for this lack of field addition in the last PR, I incidentally omitted this field at that moment.
=> [API] Added `time` field

cmd/utils/nodeflags.go, kaiax/gasless/config.go
This PR adds gasless flags to the common node flags.
=> kaiax/gasless: add gasless flags to common node flags

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/contracts/system_contracts/kip247/IKIP247.sol
I fixed the Pragma version. I also changed the version of IKIP247.sol to 0.8.24.
=> fix pragma version

kaiax/auction/impl/api.go, kaiax/auction/impl/api_test.go
Target tx must not be empty to submit a bid.
=> kaiax/auction/rpc: target tx must be incorporated

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/test/Gasless/ga.test.ts
I fixed it so that the constructor cannot set a zero address, and added a test for it.
=> fix: add require for zero address

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol
- I have changed it to use the SafeERC20 library to transfer tokens securely.
=> use SafeERC20 library

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol
I added validation of the amount received by the contract after swap.
=> Add validation of the amount received by the contract after swap

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol
I added comment about tokens supported by GSR.
=> Add comment about tokens supported by GSR

kaiax/gasless/impl/api.go, kaiax/gasless/impl/api_test.go, kaiax/gasless/impl/getter.go
I changed the reason in the result of IsGaslessTx to be of type *string. Instead of returning reason="" , it returns reason=nil.
=> chore: update IsGaslessTx API's type

.circleci/config.yml, build/Dockerfile-go1.23.7-rpmbuild-gcc7, build/Dockerfile-go1.23.7-rpmbuild-gcc7-arm, build/Dockerfile-go1.23.7-solc0.8.13-ubuntu-22.04, build/Dockerfile-go1.23.7-solc0.8.13-ubuntu-22.04-arm
- upgrade golang from 1.23.3 to 1.23.7
=> Feat/docker golang 1.23.7

kaiax/gasless/impl/api_test.go, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/tx_pool_test.go, tests/gasless_test.go
Fix A4 condition as per https://github.com/kaiachain/kips/pull/64
=> kaiax/gasless: Fix approve amount

kaiax/auction/impl/api.go
Updated `toBid` function to public so that external can utilize the module's structure.
=> kaiax/auction: `toBid` to public

.circleci/config.yml
=> ci: Remove unused credentials

.circleci/config.yml
- Supply dummy credential so AWS SDK can connect to the localstack container.
- Using us-east-1 to match dynamodb_test.go:GetTestDynamoConfig & is [localstack's default region](https://docs.localstack.cloud/references/regions-coverage/).
=> ci: Fix DynamoDB test case

kaiax/builder/impl/getter.go
=> kaiax/gasless: fix to break after finding first conflict

kerrors/kerrors.go, work/worker.go
=> kaiax/gasless: Return custom error to avoid nil pointer panic

Dockerfile
Changed OS image from Ubuntu 20 to 24
=> docker: Use Ubuntu 24.04

blockchain/state/statedb.go, work/worker.go
=> kaiax/gasless: restore statedb correctly

client/kaia_client.go, kaiax/auction/impl/api.go, kaiax/auction/impl/init.go
As auctioneer connects directly with CN, we have been introduced fine-grained APIs. This PR adds `Call` API .
Finally CN node will have four APIs:
- pending tx subscription (subscribe pending tx list)
- newhead subscription (subscribe new header)
- logs subscription (subscribe specific contract events)
- contract call RPC (call specific contract functions)
With this API set, CN works with auctioneer using minimal configuration as follows:
```
RPC_API="auction"
WS_API="auction"
```
I forgot I had added the kaia namespace in my local tests, which is why I missed adding this function.
@hyeonLewis, the modified client code(`client/kaia_client.go`) seems shadow errors by last auction calls. So, I'm considering merging them using `errors.Join()`. If you agree, let me do it in the following PR. …
=> kaiax/auction: added missing contract call function

contracts/test/Gasless/ga.test.ts, kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/errors.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/helper_test.go, kaiax/gasless/impl/tx_pool_test.go
=> kaiax/gasless: add a deadline parameter to gasless module

kaiax/gasless/impl/builder_test.go, kaiax/gasless/impl/getter.go, kaiax/gasless/impl/getter_test.go, kaiax/gasless/impl/tx_pool_test.go
=> kaiax/gasless: fix approve amount from nonzero to MaxUint

kaiax/gov/headergov/impl/consensus.go, kaiax/gov/headergov/impl/consensus_test.go, kaiax/gov/headergov/impl/init_test.go
=> kaiax/gov: Reinforce checkConsistency switch to cover all types

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/test/Gasless/ga.test.ts
- Update call to transfer to allow only KAIA transfer.
=> kaiax/gasless: update call to transfer

client/kaia_client.go
Successor of https://github.com/kaiachain/kaia/pull/377
Previously, returned an error of the last call. Now merged the two errors using `errors.Join`.
=> client: returning merged error

blockchain/state/statedb.go, blockchain/state_transition.go, blockchain/state_transition_test.go
- Removed unused function `resolveStateObject()`
- Removed unused `to` parameter in `applyAuthorization()`
=> eip7702: tidy up

contracts/contracts/system_contracts/kip247/GaslessSwapRouter.sol, contracts/contracts/system_contracts/kip247/IKIP247.sol, contracts/test/Gasless/ga.test.ts
This PR will format the Gasless contract/test code.
=> chore: Prettier GA contracts

blockchain/vm/instructions.go, blockchain/vm/jump_table.go
- This PR brings optimized code for push2 instruction from [geth](https://github.com/ethereum/go-ethereum/pull/31267)
- ethereum/go-ethereum#31267
=> blockchain/vm: Bring optimized code for push2

node/cn/handler.go, node/cn/handler_test.go
- This PR fixes overflows in `GetBlockHeaders` handler in sync with [geth](https://github.com/ethereum/go-ethereum/pull/31522)
- Also adds missing tests for `GetBlockHeaders` handler
- Our protocol related code differs a lot from geth, and I had hard time making peer communication for tests, like [geth does](https://github.com/ethereum/go-ethereum/blob/0c2ad076734e87fcc008e4718ba7b1f4f881b1fa/eth/protocols/eth/handler_test.go#L359-L368). The request sent through the pipe won't be read.
- Instead of sending request into pipe, made the test to directly call the handler function. This seems feasible because we're not trying to test the communication itself however test the handler's logics.
_Put an x in the boxes that apply. You can also …
=> node/cn: Fix overflows in `GetBlockHeaders`

blockchain/vm/memory_table.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor: use the built-in max/min to simplify the code

README.md
When updating to v2.0.0, if user import kaia-v2.0.0, user will need to specify the main branch or commit hash.
(Due to the go.mod specifications, if this is not specified, the latest version of "github.com/kaiachain/kaia" will be assumed and v1.0.3 will be selected)
ref: https://go.dev/doc/modules/version-numbers#major-version
This PR add this explanation to the README.md.
If this is a relatively large or complex change, …
=> chore: Add import guide to README.md

work/worker.go
Update `commitBundleTransaction()` log when `ApplyTransaction()` failed
- Lower log level from error to warn
- Enrich log
```
WARN[06/11,11:55:28 +09] [51|work/worker.go:931] ApplyTransaction error, restoring env   blockNum=2  txHash=0x4bae...  error=nil  receiptStatus=7
```
=> Enrich commitBundleTransaction log

consensus/istanbul/backend/api.go
- Allow `kaia.blockNumber+1` or `"pending"` argument to following APIs.
- kaia_getCouncil
- kaia_getCouncilSize
- istanbul_getValidators
- istanbul_getDemotedValidators
- Note that following APIs cannot accept the pending block because the calculation depends on the IBFT round. The round isn't determined before block finality.
- kaia_getCommittee
- kaia_getCommitteeSize
Local network example
```js
> …
```
=> istanbul: APIs allow head+1 and pending

params/config.go, params/version.go
- Mainnet #190670000 ETA 2025-07-17 10:26:21 UTC+9 ([countdown](https://kaiascope.com/blockCount/190670000))
- Version 2.0.2
=> params: Set Mainnet Prague hardfork number and Set version 2.0.2

.circleci/config.yml
- This PR supports both el7 and el9 rpm package builds
=> build: support both el7 and el9 rpm packages

.circleci/config.yml
- Currently, the rc version rpm packages are uploaded to yum repository. Previous commits didn't help.
- https://github.com/kaiachain/kaia/pull/406/commits/d228ee34b63d7ae32b71068ffa0c1264970e01c2
- https://github.com/kaiachain/kaia/pull/425/commits/b773b2f7af5bfc7d0bfa56f2b3e8420741fb52a3
- This PR skips the uploading of rpm packages to rhel s3 repository when `CIRCLE_TAG` is rc version. (e.g. v2.0.2-rc.1, v2.0.2~rc.1)
Test - It is tested on rocky8 bash shell script.
```
tags=(
"v2.0.2"
"v2.0.2-rc.1"
"v2.0.2~rc.1"
"v10.5.3"
"v1.0"
"2.0.2"
"v1.2.3-beta"
)
pat="^v[0-9]+\.[0-9]+\.[0-9]+$"
for CIRCLE_TAG in "${tags[@]}"; do
if [[ $CIRCLE_TAG =~ $pat ]]; then
echo "$CIRCLE_TAG -> matched"
else
echo "$CIRCLE_TAG -> unmatched"
fi
done
```
```
[core@yum-repo-test-amd64 ~]$ sh test.sh
v2.0.2 -> …
```
=> build: skip uploading rc version rpm packages on rhel s3 repository

common/math/big.go, common/math/integer.go, metrics/librato/client.go
Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
=> refactor: replace []byte(fmt.Sprintf) with fmt.Appendf

node/sc/bridgepeer.go, rlp/internal/rlpstruct/rlpstruct.go, snapshot/snapshot.go
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

blockchain/tx_pool.go
When the `Gasless` tx is recorded in the local journal, the txpool keeps inserting the tx into the txpool. In this PR, do not record the module tx in local to prevent redundant broadcasting and execution.
Before:
```
// Regenerate gasless transactions from the journal when the node starts up.
INFO[07/22,12:55:55 +09] [5|blockchain/tx_journal.go:119]              Loaded local transaction journal          transactions=2 dropped=0
INFO[07/22,12:55:55 +09] [5|blockchain/tx_journal.go:173]              Regenerated local transaction journal     transactions=2 accounts=1
// Since it's CN, it tried to re-execute the bundle again.
WARN[07/22,12:55:28 +09] [51|work/worker.go:948]                        ApplyTransaction error, restoring env     blockNum=17778 …
```
=> txpool: Prevent module tx be journaled

kaiax/auction/impl/builder.go, kaiax/auction/impl/init.go
Renamed `AuctionEarlyDeadline` to `AuctionEarlyDeadlineOffset`
=> kaiax/auction: Renamed `AuctionEarlyDeadline` to `AuctionEarlyDeadlineOffset`

blockchain/state_migration.go, blockchain/types/tx_internal_data_ethereum_set_code.go, datasync/downloader/statesync.go
fix some minor issues in comments
=> chore: fix some minor issues in comments

.circleci/config.yml
- Enable ws protocol in `run-rpc` job.
=> ci: Also test websocket protocol with rpc-tester

params/version.go
=> params: Set version v2.1.0

crypto/secp256k1/schnorr.go, crypto/secp256k1/secp256.go, kaiax/gasless/impl/api_test.go
fix some function names in comment
=> chore: fix some function names in comment

api/api_eth.go, blockchain/tx_pool.go, blockchain/tx_pool_test.go, blockchain/vm/access_list_tracer.go, tests/tx_validation_test.go
- This PR brings more eip-7702 related PRs from go-ethereum.
- https://github.com/kaiachain/kaia/commit/4d03d3db41596b8adcd2a1d2be56cb755861e26c commit: It excludes 7702 authorities from result in createAccessList because they are automatically added to the access list during execution. Ref: https://github.com/ethereum/go-ethereum/pull/31336/commits/2096ca7db8908d8f9ee38daf6ab30a07a595d4c3
- https://github.com/kaiachain/kaia/commit/5dcd09419f374dec36525563151a53362c82d1a9 commit: It rejects gapped tx from delegated account. Ref: https://github.com/ethereum/go-ethereum/pull/31430/commits/bdc3e5d72f423edbc6ba5098f87b84febb8d97c3, https://github.com/ethereum/go-ethereum/pull/31373/commits/42d1156472877270d831f232cfc5128056da3336
_Put an x …
=> Migrate eip-7702 related changes

consensus/gxhash/sealer.go
remove redundant word in comment
=> chore: remove redundant word in comment

cmd/homi/setup/cmd.go, cmd/homi/setup/flags.go, kaiax/gov/impl/api.go, params/config.go
Declare Osaka hardfork configuration
* Add `OsakaCompatibleBlock`
* Add `osakaCompatibleBlockNumberFlag` for **Homi**
* Add **ChainConfig**.`IsOsakaForkEnabled`
* Update **ChainConfig**.`String`
* Update **ChainConfig**.`CheckConfigForkOrder`
* Update **ChainConfig**.`checkCompatible`
* Add **Rules**.`IsOsaka`
* Prague: https://github.com/kaiachain/kaia/pull/105/files
* Kaia(Dragon): https://github.com/klaytn/klaytn/pull/2114/files
* Cancun: https://github.com/klaytn/klaytn/pull/1969/files
=> params: Declare Osaka hardfork configuration

.github/workflows/test-executor-template.yml, .github/workflows/test-other-executor-template.yml, .github/workflows/test-pr-workflow.yml
- Backport of #510 and #517 into dev.
- With this patch, the `.github` directory becomes almost identical except below diffs. That should be applied on `feat/v2.1.0` branch.
```
diff --git a/.github/workflows/test-pr-workflow.yml b/.github/workflows/test-pr-workflow.yml
index 8ad243d68..4f196252b 100644
--- a/.github/workflows/test-pr-workflow.yml
+++ b/.github/workflows/test-pr-workflow.yml
@@ -2,7 +2,7 @@ name: Testing Workflow
on:
pull_request_target:
-    types: [opened, closed, synchronize]
+    types: [opened, reopened, synchronize]
workflow_call:
permissions:
@@ -17,7 +17,9 @@ jobs:
test-linter:
uses: ./.github/workflows/test-executor-template.yml
with:
-      test_command: go run build/ci.go lint -v --new-from-rev=dev
+      test_command: |
+        git fetch origin dev:dev
+ …
```
=> ci: Fix GitHub Actions Testing Workflow

.github/workflows/test-pr-workflow.yml
=> ci: add logic to check branch to checkout for linter

accounts/abi/unpack_test.go, datasync/downloader/downloader.go, networks/rpc/client_test.go, node/api_admin_network_test.go, node/node_test.go, node/sc/mainbridge.go, node/sc/subbridge.go, rlp/decode_test.go, rlp/rlpgen/gen_test.go, tests/state_test.go
The new version of Go has been optimized, and variables do not need to be reassigned.
=> refactor: omit unnecessary reassignment

contracts/contracts/system_contracts/auction/AuctionFeeVault.sol
Use `.send` to restrict the gas consumption and explicitly check the result.
=> contract: Use send instead of call

kaiax/auction/bid.go, kaiax/auction/errors.go
This PR checks signature validity when recovering the searhcer/auctioneer during bid validation.
=> kaiax/auction: Validate signature malleability

contracts/contracts/system_contracts/auction/AuctionFeeVault.sol, contracts/contracts/system_contracts/auction/IAuctionFeeVault.sol
In https://github.com/kaiachain/kaia/pull/541, the payback failed log isn't clear enough. This PR fixes a log to be more aligned with the context.
=> contract: Use clear log name
